// Generated by `scripts/util/generate_inspection_short_names.py`

package icu.windea.pls.lang.inspections

@Suppress("unused")
object ChronicleInspections {
    object Overrides {
        /** @see icu.windea.pls.lang.inspections.overrides.OverrideForFileInspection */
        const val OverrideForFile = "ParadoxOverrideForFile"
        /** @see icu.windea.pls.lang.inspections.overrides.OverrideForScriptedVariableInspection */
        const val OverrideForScriptedVariable = "ParadoxOverrideForScriptedVariable"
        /** @see icu.windea.pls.lang.inspections.overrides.OverrideForDefinitionInspection */
        const val OverrideForDefinition = "ParadoxOverrideForDefinition"
        /** @see icu.windea.pls.lang.inspections.overrides.OverrideForDefineVariableInspection */
        const val OverrideForDefineVariable = "ParadoxOverrideForDefineVariable"
        /** @see icu.windea.pls.lang.inspections.overrides.IncorrectOverrideForScriptedVariableInspection */
        const val IncorrectOverrideForScriptedVariable = "ParadoxIncorrectOverrideForScriptedVariable"
        /** @see icu.windea.pls.lang.inspections.overrides.IncorrectOverrideForDefinitionInspection */
        const val IncorrectOverrideForDefinition = "ParadoxIncorrectOverrideForDefinition"
        /** @see icu.windea.pls.lang.inspections.overrides.IncorrectOverrideForDefineVariableInspection */
        const val IncorrectOverrideForDefineVariable = "ParadoxIncorrectOverrideForDefineVariable"
    }

    object Script {
        // Paradox Script/Common

        /** @see icu.windea.pls.lang.inspections.script.common.IncorrectFileEncodingInspection */
        const val IncorrectFileEncoding = "ParadoxScriptIncorrectFileEncoding"
        /** @see icu.windea.pls.lang.inspections.script.common.UnmatchedFileInspection */
        const val UnmatchedFile = "ParadoxScriptUnmatchedFile"
        /** @see icu.windea.pls.lang.inspections.script.common.DuplicateScriptedVariablesInspection */
        const val DuplicateScriptedVariables = "ParadoxScriptDuplicateScriptedVariables"
        /** @see icu.windea.pls.lang.inspections.script.common.MissingLocalisationInspection */
        const val MissingLocalisation = "ParadoxScriptMissingLocalisation"
        /** @see icu.windea.pls.lang.inspections.script.common.MissingImageInspection */
        const val MissingImage = "ParadoxScriptMissingImage"
        /** @see icu.windea.pls.lang.inspections.script.common.UnresolvedScriptedVariableInspection */
        const val UnresolvedScriptedVariable = "ParadoxScriptUnresolvedScriptedVariable"
        /** @see icu.windea.pls.lang.inspections.script.common.UnusedParameterInspection */
        const val UnusedParameter = "ParadoxScriptUnusedParameter"
        /** @see icu.windea.pls.lang.inspections.script.common.MissingParameterInspection */
        const val MissingParameter = "ParadoxScriptMissingParameter"
        /** @see icu.windea.pls.lang.inspections.script.common.UnusedDynamicValueInspection */
        const val UnusedDynamicValue = "ParadoxScriptUnusedDynamicValue"
        /** @see icu.windea.pls.lang.inspections.script.common.UnsetDynamicValueInspection */
        const val UnsetDynamicValue = "ParadoxScriptUnsetDynamicValue"
        /** @see icu.windea.pls.lang.inspections.script.common.IncorrectSyntaxInspection */
        const val IncorrectSyntax = "ParadoxScriptIncorrectSyntax"
        /** @see icu.windea.pls.lang.inspections.script.common.UnsupportedParameterInspection */
        const val UnsupportedParameter = "ParadoxScriptUnsupportedParameter"
        /** @see icu.windea.pls.lang.inspections.script.common.UnsupportedConditionalBlockInspection */
        const val UnsupportedConditionalBlock = "ParadoxScriptUnsupportedConditionalBlock"
        /** @see icu.windea.pls.lang.inspections.script.common.UnsupportedInlineMathInspection */
        const val UnsupportedInlineMath = "ParadoxScriptUnsupportedInlineMath"
        /** @see icu.windea.pls.lang.inspections.script.common.UnsupportedRecursionInspection */
        const val UnsupportedRecursion = "ParadoxScriptUnsupportedRecursion"

        // Paradox Script/Statements

        /** @see icu.windea.pls.lang.inspections.script.statement.ConditionalStatementToPropertyFormInspection */
        const val ConditionalStatementToPropertyForm = "ParadoxScriptConditionalStatementToPropertyForm"
        /** @see icu.windea.pls.lang.inspections.script.statement.ConditionalStatementToBlockFormInspection */
        const val ConditionalStatementToBlockForm = "ParadoxScriptConditionalStatementToBlockForm"
        /** @see icu.windea.pls.lang.inspections.script.statement.ScopeCallStatementToSafeFormInspection */
        const val ScopeCallToSafeForm = "ParadoxScriptScopeCallToSafeForm"
        /** @see icu.windea.pls.lang.inspections.script.statement.ScopeCallStatementToNormalFormInspection */
        const val ScopeCallToNormalForm = "ParadoxScriptScopeCallToNormalForm"
        /** @see icu.windea.pls.lang.inspections.script.statement.ScopeCallStatementToChainedFormInspection */
        const val ScopeCallToChainedForm = "ParadoxScriptScopeCallToChainedForm"
        /** @see icu.windea.pls.lang.inspections.script.statement.ScopeCallStatementToNestedFormInspection */
        const val ScopeCallToNestedForm = "ParadoxScriptScopeCallToNestedForm"

        // Paradox Script/Expressions

        /** @see icu.windea.pls.lang.inspections.script.expression.MissingExpressionInspection */
        const val MissingExpression = "ParadoxScriptMissingExpression"
        /** @see icu.windea.pls.lang.inspections.script.expression.TooManyExpressionInspection */
        const val TooManyExpression = "ParadoxScriptTooManyExpression"
        /** @see icu.windea.pls.lang.inspections.script.expression.UnresolvedExpressionInspection */
        const val UnresolvedExpression = "ParadoxScriptUnresolvedExpression"
        /** @see icu.windea.pls.lang.inspections.script.expression.IncorrectExpressionInspection */
        const val IncorrectExpression = "ParadoxScriptIncorrectExpression"
        /** @see icu.windea.pls.lang.inspections.script.expression.ConflictingExpressionInspection */
        const val ConflictingExpression = "ParadoxScriptConflictingExpression"
        /** @see icu.windea.pls.lang.inspections.script.expression.UnresolvedPathReferenceInspection */
        const val UnresolvedPathReference = "ParadoxScriptUnresolvedPathReference"
        /** @see icu.windea.pls.lang.inspections.script.expression.IncorrectPathReferenceInspection */
        const val IncorrectPathReference = "ParadoxScriptIncorrectPathReference"

        // Paradox Script/Complex expressions

        /** @see icu.windea.pls.lang.inspections.script.complexExpression.IncorrectScopeFieldExpressionInspection */
        const val IncorrectScopeFieldExpression = "ParadoxScriptIncorrectScopeFieldExpression"
        /** @see icu.windea.pls.lang.inspections.script.complexExpression.IncorrectValueFieldExpressionInspection */
        const val IncorrectValueFieldExpression = "ParadoxScriptIncorrectValueFieldExpression"
        /** @see icu.windea.pls.lang.inspections.script.complexExpression.IncorrectVariableFieldExpressionInspection */
        const val IncorrectVariableFieldExpression = "ParadoxScriptIncorrectVariableFieldExpression"
        /** @see icu.windea.pls.lang.inspections.script.complexExpression.IncorrectDynamicValueExpressionInspection */
        const val IncorrectDynamicValueExpression = "ParadoxScriptIncorrectDynamicValueExpression"
        /** @see icu.windea.pls.lang.inspections.script.complexExpression.IncorrectScriptValueReferenceExpressionInspection */
        const val IncorrectScriptValueReferenceExpression = "ParadoxScriptIncorrectScriptValueReferenceExpression"
        /** @see icu.windea.pls.lang.inspections.script.complexExpression.IncorrectDefineReferenceExpressionInspection */
        const val IncorrectDefineReferenceExpression = "ParadoxScriptIncorrectDefineReferenceExpression"
        /** @see icu.windea.pls.lang.inspections.script.complexExpression.IncorrectArrayDefineReferenceExpressionInspection */
        const val IncorrectArrayDefineReferenceExpression = "ParadoxScriptIncorrectArrayDefineReferenceExpression"
        /** @see icu.windea.pls.lang.inspections.script.complexExpression.IncorrectTagsExpressionInspection */
        const val IncorrectTagsExpression = "ParadoxScriptIncorrectTagsExpression"
        /** @see icu.windea.pls.lang.inspections.script.complexExpression.IncorrectDatabaseObjectExpressionInspection */
        const val IncorrectDatabaseObjectExpression = "ParadoxScriptIncorrectDatabaseObjectExpression"
        /** @see icu.windea.pls.lang.inspections.script.complexExpression.IncorrectNameFormatExpressionInspection */
        const val IncorrectNameFormatExpression = "ParadoxScriptIncorrectNameFormatExpression"

        // Paradox Script/Events

        /** @see icu.windea.pls.lang.inspections.script.event.IncorrectEventIdInspection */
        const val IncorrectEventId = "ParadoxScriptIncorrectEventId"
        /** @see icu.windea.pls.lang.inspections.script.event.IncorrectEventNamespaceInspection */
        const val IncorrectEventNamespace = "ParadoxScriptIncorrectEventNamespace"
        /** @see icu.windea.pls.lang.inspections.script.event.MissingEventNamespaceInspection */
        const val MissingEventNamespace = "ParadoxScriptMissingEventNamespace"
        /** @see icu.windea.pls.lang.inspections.script.event.MismatchedEventIdInspection */
        const val MismatchedEventId = "ParadoxScriptMismatchedEventId"
        /** @see icu.windea.pls.lang.inspections.script.event.NonTriggeredEventInspection */
        const val NonTriggeredEvent = "ParadoxScriptNonTriggeredEvent"

        // Paradox Script/Inline scripts

        /** @see icu.windea.pls.lang.inspections.script.inlineScript.UnusedInlineScriptInspection */
        const val UnusedInlineScript = "ParadoxScriptUnusedInlineScript"
        /** @see icu.windea.pls.lang.inspections.script.inlineScript.ConflictingInlineScriptUsageInspection */
        const val ConflictingInlineScriptUsage = "ParadoxScriptConflictingInlineScriptUsage"
        /** @see icu.windea.pls.lang.inspections.script.inlineScript.RecursiveInlineScriptUsageInspection */
        const val RecursiveInlineScriptUsage = "ParadoxScriptRecursiveInlineScriptUsage"
        /** @see icu.windea.pls.lang.inspections.script.inlineScript.UnsupportedInlineScriptUsageInspection */
        const val UnsupportedInlineScriptUsage = "ParadoxScriptUnsupportedInlineScriptUsage"

        // Paradox Script/Definition injections

        /** @see icu.windea.pls.lang.inspections.script.definitionInjection.UnsupportedDefinitionInjectionUsageInspection */
        const val UnsupportedDefinitionInjectionUsage = "ParadoxScriptUnsupportedDefinitionInjectionUsage"
        /** @see icu.windea.pls.lang.inspections.script.definitionInjection.IncorrectDefinitionInjectionUsageInspection */
        const val IncorrectDefinitionInjectionUsage = "ParadoxScriptIncorrectDefinitionInjectionUsage"

        // Paradox Script/Scope issues

        /** @see icu.windea.pls.lang.inspections.script.scope.IncorrectScopeInspection */
        const val IncorrectScope = "ParadoxScriptIncorrectScope"
        /** @see icu.windea.pls.lang.inspections.script.scope.IncorrectScopeSwitchInspection */
        const val IncorrectScopeSwitch = "ParadoxScriptIncorrectScopeSwitch"
        /** @see icu.windea.pls.lang.inspections.script.scope.IncorrectScopeLinkChainInspection */
        const val IncorrectScopeLinkChain = "ParadoxScriptIncorrectScopeLinkChain"
        /** @see icu.windea.pls.lang.inspections.script.scope.ConflictingScopeContextInferenceInspection */
        const val ConflictingScopeContextInference = "ParadoxScriptConflictingScopeContextInference"
    }

    object Localisation {
        // Paradox Localisation/Common

        /** @see icu.windea.pls.lang.inspections.localisation.common.IncorrectFileEncodingInspection */
        const val IncorrectFileEncoding = "ParadoxLocalisationIncorrectFileEncoding"
        /** @see icu.windea.pls.lang.inspections.localisation.common.IncorrectFileNameInspection */
        const val IncorrectFileName = "ParadoxLocalisationIncorrectFileName"
        /** @see icu.windea.pls.lang.inspections.localisation.common.DuplicatePropertiesInspection */
        const val DuplicateProperties = "ParadoxLocalisationDuplicateProperties"
        /** @see icu.windea.pls.lang.inspections.localisation.common.MultipleLocalesInspection */
        const val MultipleLocales = "ParadoxLocalisationMultipleLocales"
        /** @see icu.windea.pls.lang.inspections.localisation.common.MissingLocaleInspection */
        const val MissingLocale = "ParadoxLocalisationMissingLocale"
        /** @see icu.windea.pls.lang.inspections.localisation.common.MissingLocalisationInspection */
        const val MissingLocalisation = "ParadoxLocalisationMissingLocalisation"
        /** @see icu.windea.pls.lang.inspections.localisation.common.UnsupportedLocaleInspection */
        const val UnsupportedLocale = "ParadoxLocalisationUnsupportedLocale"
        /** @see icu.windea.pls.lang.inspections.localisation.common.UnresolvedColorInspection */
        const val UnresolvedColor = "ParadoxLocalisationUnresolvedColor"
        /** @see icu.windea.pls.lang.inspections.localisation.common.UnresolvedScriptedVariableInspection */
        const val UnresolvedScriptedVariable = "ParadoxLocalisationUnresolvedScriptedVariable"
        /** @see icu.windea.pls.lang.inspections.localisation.common.UnresolvedIconInspection */
        const val UnresolvedIcon = "ParadoxLocalisationUnresolvedIcon"
        /** @see icu.windea.pls.lang.inspections.localisation.common.UnresolvedConceptInspection */
        const val UnresolvedConcept = "ParadoxLocalisationUnresolvedConcept"
        /** @see icu.windea.pls.lang.inspections.localisation.common.UnresolvedTextFormatInspection */
        const val UnresolvedTextFormat = "ParadoxLocalisationUnresolvedTextFormat"
        /** @see icu.windea.pls.lang.inspections.localisation.common.UnresolvedTextIconInspection */
        const val UnresolvedTextIcon = "ParadoxLocalisationUnresolvedTextIcon"
        /** @see icu.windea.pls.lang.inspections.localisation.common.IncorrectSyntaxInspection */
        const val IncorrectSyntax = "ParadoxLocalisationIncorrectSyntax"
        /** @see icu.windea.pls.lang.inspections.localisation.common.UnsupportedRecursionInspection */
        const val UnsupportedRecursion = "ParadoxLocalisationUnsupportedRecursion"

        // Paradox Localisation/Complex expressions

        /** @see icu.windea.pls.lang.inspections.localisation.complexExpression.IncorrectCommandExpressionInspection */
        const val IncorrectCommandExpression = "ParadoxLocalisationIncorrectCommandExpression"
        /** @see icu.windea.pls.lang.inspections.localisation.complexExpression.IncorrectDatabaseObjectExpressionInspection */
        const val IncorrectDatabaseObjectExpression = "ParadoxLocalisationIncorrectDatabaseObjectExpression"

        // Paradox Localisation/Scope issues

        /** @see icu.windea.pls.lang.inspections.localisation.scope.IncorrectScopeInspection */
        const val IncorrectScope = "ParadoxLocalisationIncorrectScope"
        /** @see icu.windea.pls.lang.inspections.localisation.scope.IncorrectScopeSwitchInspection */
        const val IncorrectScopeSwitch = "ParadoxLocalisationIncorrectScopeSwitch"
        /** @see icu.windea.pls.lang.inspections.localisation.scope.IncorrectScopeLinkChainInspection */
        const val IncorrectScopeLinkChain = "ParadoxLocalisationIncorrectScopeLinkChain"
    }

    object Csv {
        // Paradox CSV/Common

        /** @see icu.windea.pls.lang.inspections.csv.common.IncorrectFileEncodingInspection */
        const val IncorrectFileEncoding = "ParadoxCsvIncorrectFileEncoding"
        /** @see icu.windea.pls.lang.inspections.csv.common.UnmatchedFileInspection */
        const val UnmatchedFile = "ParadoxCsvUnmatchedFile"

        // Paradox CSV/Expressions

        /** @see icu.windea.pls.lang.inspections.csv.expression.UnresolvedExpressionInspection */
        const val UnresolvedExpression = "ParadoxCsvUnresolvedExpression"
        /** @see icu.windea.pls.lang.inspections.csv.expression.IncorrectExpressionInspection */
        const val IncorrectExpression = "ParadoxCsvIncorrectExpression"
        /** @see icu.windea.pls.lang.inspections.csv.expression.IncorrectColumnNameInspection */
        const val IncorrectColumnName = "ParadoxCsvIncorrectColumnName"
        /** @see icu.windea.pls.lang.inspections.csv.expression.IncorrectColumnSizeInspection */
        const val IncorrectColumnSize = "ParadoxCsvIncorrectColumnSize"
    }

    object Lints {
        /** @see icu.windea.pls.lang.inspections.lints.ChronicleTigerLintInspection */
        const val Tiger = "ChronicleTigerLint"
    }
}
