package icu.windea.pls.script.psi

import com.intellij.psi.TokenType
import com.intellij.psi.tree.TokenSet
import icu.windea.pls.script.psi.ParadoxScriptElementTypes.*

object ParadoxScriptTokenSets {
    @JvmField val WHITE_SPACES = TokenSet.create(TokenType.WHITE_SPACE)
    @JvmField val COMMENTS = TokenSet.create(COMMENT)
    @JvmField val STRING_LITERALS = TokenSet.create(STRING_TOKEN)

    @JvmField val IDENTIFIER_TOKENS = TokenSet.create(SCRIPTED_VARIABLE_NAME_TOKEN, SCRIPTED_VARIABLE_REFERENCE_TOKEN, PROPERTY_KEY_TOKEN, STRING_TOKEN, CONDITION_PARAMETER_TOKEN, PARAMETER_TOKEN)
    @JvmField val COMMENT_TOKENS = TokenSet.create(COMMENT)
    @JvmField val LITERAL_TOKENS = TokenSet.create(PROPERTY_KEY_TOKEN, STRING_TOKEN)

    @JvmField val MERGED_TOKENS = TokenSet.create(TokenType.WHITE_SPACE, PROPERTY_KEY_TOKEN, STRING_TOKEN, SCRIPTED_VARIABLE_NAME_TOKEN, SCRIPTED_VARIABLE_REFERENCE_TOKEN)
    @JvmField val SCRIPTED_VARIABLE_NAME_TOKENS = TokenSet.create(SCRIPTED_VARIABLE_NAME_TOKEN)
    @JvmField val SCRIPTED_VARIABLE_VALUE_TOKENS = TokenSet.create(BOOLEAN_TOKEN, INT_TOKEN, FLOAT_TOKEN, STRING_TOKEN)
    @JvmField val SCRIPTED_VARIABLE_REFERENCE_TOKENS = TokenSet.create(SCRIPTED_VARIABLE_REFERENCE_TOKEN)
    @JvmField val STRING_TOKENS = TokenSet.create(STRING_TOKEN)
    @JvmField val KEY_OR_STRING_TOKENS = TokenSet.create(PROPERTY_KEY_TOKEN, STRING_TOKEN)
    @JvmField val STRING_EXPRESSION_TOKENS = TokenSet.create(PROPERTY_KEY_TOKEN, STRING_TOKEN)
    @JvmField val VARIABLE_VALUE_TOKENS = TokenSet.create(INT_TOKEN, FLOAT_TOKEN, STRING_TOKEN)
    @JvmField val PARAMETER_TOKENS = TokenSet.create(PARAMETER_TOKEN, CONDITION_PARAMETER_TOKEN)
    @JvmField val INTERPOLATION_TOKENS = TokenSet.create(PARAMETER, INLINE_CONDITIONAL_BLOCK)
    @JvmField val MEMBER_CONTEXT_TOKENS = TokenSet.create(PROPERTY, BLOCK, ROOT_BLOCK, CONDITIONAL_BLOCK)

    @JvmField val PROPERTY_SEPARATOR_TOKENS = TokenSet.create(EQUAL_SIGN, NOT_EQUAL_SIGN, LT_SIGN, GT_SIGN, LE_SIGN, GE_SIGN, SAFE_ASSIGN_SIGN, SAFE_ASSIGN_SIGN, SAFE_CALL_ASSIGN_SIGN)
    @JvmField val ASSIGN_OPERATOR_TOKENS = TokenSet.create(EQUAL_SIGN, SAFE_ASSIGN_SIGN, SAFE_CALL_ASSIGN_SIGN)
    @JvmField val SAFE_OPERATOR_TOKENS = TokenSet.create(SAFE_ASSIGN_SIGN, SAFE_CALL_ASSIGN_SIGN)
    @JvmField val COMPARISON_OPERATOR_TOKENS = TokenSet.create(NOT_EQUAL_SIGN, LT_SIGN, GT_SIGN, LE_SIGN, GE_SIGN)

    @JvmField val SNIPPET_TOKENS = TokenSet.create(PROPERTY_KEY_TOKEN, STRING_TOKEN, SCRIPTED_VARIABLE_NAME_TOKEN, SCRIPTED_VARIABLE_REFERENCE_TOKEN)
    @JvmField val LEFT_SNIPPET_TOKENS = TokenSet.create(AT, SCRIPTED_VARIABLE_NAME_TOKEN, PROPERTY_KEY_TOKEN)
    @JvmField val RIGHT_SNIPPET_TOKENS = TokenSet.create(STRING_TOKEN, SCRIPTED_VARIABLE_REFERENCE_TOKEN)
    @JvmField val BREAK_SNIPPET_TOKENS = TokenSet.create(TokenType.WHITE_SPACE, COMMENT)
}
