package icu.windea.pls.config

import icu.windea.pls.PlsBundle
import icu.windea.pls.PlsIcons
import icu.windea.pls.model.constants.PlsStrings

@Suppress("unused")
object CwtConfigTypes {
    val Type = CwtConfigType.builder("type")
        .icon(PlsIcons.Nodes.Type)
        .prefix(PlsStrings.typePrefix)
        .description(PlsBundle.message("cwt.config.description.type"))
        .build()
    val Subtype = CwtConfigType.builder("subtype")
        .icon(PlsIcons.Nodes.Type)
        .prefix(PlsStrings.subtypePrefix)
        .description(PlsBundle.message("cwt.config.description.subtype"))
        .build()
    val Row = CwtConfigType.builder("row")
        .icon(PlsIcons.Nodes.Row)
        .prefix(PlsStrings.rowPrefix)
        .description(PlsBundle.message("cwt.config.description.row"))
        .build()
    val Enum = CwtConfigType.builder("enum")
        .icon(PlsIcons.Nodes.Enum)
        .prefix(PlsStrings.enumPrefix)
        .description(PlsBundle.message("cwt.config.description.enum"))
        .build()
    val ComplexEnum = CwtConfigType.builder("complex enum")
        .icon(PlsIcons.Nodes.Enum)
        .prefix(PlsStrings.complexEnumPrefix)
        .description(PlsBundle.message("cwt.config.description.complexEnum"))
        .build()
    val EnumValue = CwtConfigType.builder("enum value", "enums").reference()
        .icon(PlsIcons.Nodes.EnumValue)
        .prefix(PlsStrings.enumValuePrefix)
        .description(PlsBundle.message("cwt.config.description.enumValue"))
        .build()
    val DynamicValueType = CwtConfigType.builder("dynamic value type")
        .icon(PlsIcons.Nodes.DynamicValueType)
        .prefix(PlsStrings.dynamicValueTypePrefix)
        .description(PlsBundle.message("cwt.config.description.dynamicValueType"))
        .build()
    val DynamicValue = CwtConfigType.builder("dynamic value", "values").reference()
        .icon(PlsIcons.Nodes.DynamicValue)
        .prefix(PlsStrings.dynamicValuePrefix)
        .description(PlsBundle.message("cwt.config.description.dynamicValue"))
        .build()
    val SingleAlias = CwtConfigType.builder("single alias")
        .icon(PlsIcons.Nodes.Alias)
        .prefix(PlsStrings.singleAliasPrefix)
        .description(PlsBundle.message("cwt.config.description.singleAlias"))
        .build()
    val Alias = CwtConfigType.builder("alias")
        .icon(PlsIcons.Nodes.Alias)
        .prefix(PlsStrings.aliasPrefix)
        .description(PlsBundle.message("cwt.config.description.alias"))
        .build()
    val Directive = CwtConfigType.builder("directive")
        .icon(PlsIcons.Nodes.Directive)
        .prefix(PlsStrings.directivePrefix)
        .description(PlsBundle.message("cwt.config.description.directive"))
        .build()
    val Link = CwtConfigType.builder("link").reference()
        .icon(PlsIcons.Nodes.Link)
        .prefix(PlsStrings.linkPrefix)
        .description(PlsBundle.message("cwt.config.description.link"))
        .build()
    val LocalisationLink = CwtConfigType.builder("localisation link").reference()
        .icon(PlsIcons.Nodes.Link)
        .prefix(PlsStrings.localisationLinkPrefix)
        .description(PlsBundle.message("cwt.config.description.localisationLink"))
        .build()
    val LocalisationPromotion = CwtConfigType.builder("localisation promotion").reference()
        .icon(PlsIcons.Nodes.Link)
        .prefix(PlsStrings.localisationPromotionPrefix)
        .description(PlsBundle.message("cwt.config.description.localisationPromotion"))
        .build()
    val LocalisationCommand = CwtConfigType.builder("localisation command").reference()
        .icon(PlsIcons.Nodes.LocalisationCommandField)
        .prefix(PlsStrings.localisationCommandPrefix)
        .description(PlsBundle.message("cwt.config.description.localisationCommand"))
        .build()
    val ModifierCategory = CwtConfigType.builder("modifier category").reference()
        .icon(PlsIcons.Nodes.ModifierCategory)
        .prefix(PlsStrings.modifierCategoryPrefix)
        .description(PlsBundle.message("cwt.config.description.modifierCategory"))
        .build()
    val Modifier = CwtConfigType.builder("modifier").reference()
        .icon(PlsIcons.Nodes.Modifier)
        .prefix(PlsStrings.modifierPrefix)
        .description(PlsBundle.message("cwt.config.description.modifier"))
        .build()
    val Trigger = CwtConfigType.builder("trigger").reference()
        .icon(PlsIcons.Nodes.Trigger)
        .prefix(PlsStrings.triggerPrefix)
        .description(PlsBundle.message("cwt.config.description.trigger"))
        .build()
    val Effect = CwtConfigType.builder("effect").reference()
        .icon(PlsIcons.Nodes.Effect)
        .prefix(PlsStrings.effectPrefix)
        .description(PlsBundle.message("cwt.config.description.effect"))
        .build()
    val Scope = CwtConfigType.builder("scope").reference()
        .icon(PlsIcons.Nodes.Scope)
        .prefix(PlsStrings.scopePrefix)
        .description(PlsBundle.message("cwt.config.description.scope"))
        .build()
    val ScopeGroup = CwtConfigType.builder("scope group").reference()
        .icon(PlsIcons.Nodes.Scope)
        .prefix(PlsStrings.scopeGroupPrefix)
        .description(PlsBundle.message("cwt.config.description.scopeGroup"))
        .build()
    val DatabaseObjectType = CwtConfigType.builder("database object type").reference()
        .icon(PlsIcons.Nodes.DatabaseObjectType)
        .prefix(PlsStrings.databaseObjectTypePrefix)
        .description(PlsBundle.message("cwt.config.description.databaseObjectType"))
        .build()
    val SystemScope = CwtConfigType.builder("system scope").reference()
        .icon(PlsIcons.Nodes.SystemScope)
        .prefix(PlsStrings.systemScopePrefix)
        .description(PlsBundle.message("cwt.config.description.systemScope"))
        .build()
    val Locale = CwtConfigType.builder("locale").reference()
        .icon(PlsIcons.Nodes.LocalisationLocale)
        .prefix(PlsStrings.localePrefix)
        .description(PlsBundle.message("cwt.config.description.locale"))
        .build()

    val ExtendedScriptedVariable = CwtConfigType.builder("extended scripted variable")
        .icon(PlsIcons.Nodes.ScriptedVariableConfig)
        .prefix(PlsStrings.scriptedVariablePrefix)
        .build()
    val ExtendedDefinition = CwtConfigType.builder("extended definition")
        .icon(PlsIcons.Nodes.DefinitionConfig)
        .prefix(PlsStrings.definitionPrefix)
        .build()
    val ExtendedGameRule = CwtConfigType.builder("extended game rule")
        .icon(PlsIcons.Nodes.DefinitionConfig)
        .prefix(PlsStrings.gameRulePrefix)
        .build()
    val ExtendedOnAction = CwtConfigType.builder("extended on action")
        .icon(PlsIcons.Nodes.DefinitionConfig)
        .prefix(PlsStrings.onActionPrefix)
        .build()
    val ExtendedInlineScript = CwtConfigType.builder("extended inline script")
        .icon(PlsIcons.Nodes.InlineScriptConfig)
        .prefix(PlsStrings.inlineScriptPrefix)
        .build()
    val ExtendedParameter = CwtConfigType.builder("extended parameter")
        .icon(PlsIcons.Nodes.ParameterConfig)
        .prefix(PlsStrings.parameterPrefix)
        .build()
    val ExtendedDynamicValue = CwtConfigType.builder("extended dynamic value")
        .icon(PlsIcons.Nodes.DynamicValueConfig)
        .prefix(PlsStrings.dynamicValuePrefix)
        .build()
    val ExtendedComplexEnumValue = CwtConfigType.builder("extended complex enum value")
        .icon(PlsIcons.Nodes.EnumValueConfig)
        .prefix(PlsStrings.complexEnumValuePrefix)
        .build()
}
