# Copyright (c) 2021 DragonKnightOfBreeze Windea <dk_breeze@qq.com>
# All rights reserved.

"""generate_inspection_short_names.py — Regenerate `ChronicleInspections` from the inspections XML.

This script reads ``src/main/resources/META-INF/chronicle-inspections.xml`` and
regenerates ``src/main/kotlin/icu/windea/pls/lang/inspections/ChronicleInspections.kt``,
which exposes every bundled inspection short name as a Kotlin constant, grouped by region.

For each ``<localInspection>`` entry a constant ``val X = "Y"`` is generated where
``X`` is derived from the short name ``Y`` by stripping the prefix specific to the
enclosing object (and, for the Lints object, also the ``Lint`` suffix), as
configured in ``OBJECT_NAME_MAP``. XML comments of the form ``<!-- region Foo/Bar -->``
become ``// Foo/Bar`` comments for grouping in the generated Kotlin code,
and the generated header comment is followed by a blank line.

Usage:
  python scripts/util/generate_inspection_short_names.py
  python scripts/util/generate_inspection_short_names.py --check
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

GENERATED_HEADER = "// Generated by `scripts/util/generate_inspection_short_names.py`"
PACKAGE_NAME = "icu.windea.pls.lang.inspections"
OBJECT_NAME = "ChronicleInspections"

XML_FILE = Path("src/main/resources/META-INF/chronicle-inspections.xml")
KT_FILE = Path("src/main/kotlin/icu/windea/pls/lang/inspections/ChronicleInspections.kt")

# Maps a top-level XML region name to the nested object name and the short-name
# stripping rules (prefix, optional suffix) used to derive the constant names.
OBJECT_NAME_MAP: dict[str, tuple[str, str, str | None]] = {
    "Overrides": ("Overrides", "Paradox", None),
    "Paradox Script": ("Script", "ParadoxScript", None),
    "Paradox Localisation": ("Localisation", "ParadoxLocalisation", None),
    "Paradox CSV": ("Csv", "ParadoxCsv", None),
    "Linting Tools": ("Lints", "Chronicle", "Lint"),
}

REGION_PREFIX = "region "


class _CommentedTreeBuilder(ET.TreeBuilder):
    """TreeBuilder that keeps XML comments as elements in the tree."""

    def comment(self, data: str) -> None:
        self.start(ET.Comment, {})
        self.data(data)
        self.end(ET.Comment)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Regenerate ChronicleInspections from the inspections XML.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check whether the generated file is up to date without writing changes.",
    )
    return parser.parse_args()


def build_region_items(extensions: ET.Element) -> list[tuple]:
    """Collect inspections into a tree of regions from the ``<extensions>`` element.

    Returns a list of ``("region", node)`` items, where each *node* is a dict with
    ``name`` and an ordered ``items`` list of ``("region", node)`` or
    ``("inspection", shortName, implementationClass)`` tuples.
    """
    root_items: list[tuple] = []
    stack: list[dict] = []

    for child in extensions:
        if child.tag is ET.Comment:
            text = (child.text or "").strip()
            if text.startswith(REGION_PREFIX):
                name = text[len(REGION_PREFIX):].strip()
                node = {"name": name, "items": []}
                if stack:
                    stack[-1]["items"].append(("region", node))
                else:
                    root_items.append(("region", node))
                stack.append(node)
            elif text == "endregion":
                if stack:
                    stack.pop()
        elif child.tag == "localInspection":
            if not stack:
                continue
            short_name = (child.get("shortName") or "").strip()
            implementation_class = (child.get("implementationClass") or "").strip()
            if not short_name:
                continue
            stack[-1]["items"].append(("inspection", short_name, implementation_class))

    return root_items


def short_const_name(short_name: str, prefix: str, suffix: str | None) -> str:
    """Derive the constant name from an inspection short name.

    Returns *short_name* with the *prefix* removed, and with the *suffix* removed
    as well when it is present (per the naming rules of the enclosing object).
    """
    name = short_name
    if name.startswith(prefix):
        name = name[len(prefix):]
    if suffix is not None and name.endswith(suffix):
        name = name[: -len(suffix)]
    return name


def _append_items(lines: list[str], items: list[tuple], indent: str, prefix: str, suffix: str | None) -> None:
    for index, item in enumerate(items):
        if item[0] == "region":
            _, node = item
            lines.append(f"{indent}// {node['name']}")
            lines.append("")
            _append_items(lines, node["items"], indent, prefix, suffix)
            if index != len(items) - 1:
                lines.append("")
        else:
            _, short_name, implementation_class = item
            lines.append(f"{indent}/** @see {implementation_class} */")
            lines.append(f'{indent}const val {short_const_name(short_name, prefix, suffix)} = "{short_name}"')


def generate_kt(root_items: list[tuple]) -> str:
    """Generate the complete Kotlin source for ``ChronicleInspections``."""
    lines = [
        GENERATED_HEADER,
        "",
        f"package {PACKAGE_NAME}",
        "",
        '@Suppress("unused")',
        f"object {OBJECT_NAME} {{",
    ]
    indent = "    "
    for index, (kind, node) in enumerate(root_items):
        try:
            object_name, prefix, suffix = OBJECT_NAME_MAP[node["name"]]
        except KeyError:
            raise ValueError(f"Unknown top-level region: {node['name']!r}. Update OBJECT_NAME_MAP.") from None
        if index > 0:
            lines.append("")
        lines.append(f"{indent}object {object_name} {{")
        _append_items(lines, node["items"], indent * 2, prefix, suffix)
        lines.append(f"{indent}}}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[2]
    xml_file = (repo_root / XML_FILE).resolve()
    kt_file = (repo_root / KT_FILE).resolve()

    if not xml_file.is_file():
        print(f"ERROR: inspections XML not found: {xml_file}", file=sys.stderr)
        return 1

    parser = ET.XMLParser(target=_CommentedTreeBuilder())
    tree = ET.parse(xml_file, parser=parser)
    extensions = tree.getroot().find("extensions")
    if extensions is None:
        print(f"ERROR: <extensions> element not found in: {xml_file}", file=sys.stderr)
        return 1

    root_items = build_region_items(extensions)
    generated = generate_kt(root_items)

    if args.check:
        existing = kt_file.read_text(encoding="utf-8") if kt_file.is_file() else None
        if existing == generated:
            print(f"ChronicleInspections is up to date: {kt_file}")
            return 0
        print(f"ChronicleInspections requires regeneration: {kt_file}", file=sys.stderr)
        return 1

    kt_file.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Generated: {kt_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
