### localisation locale
  
locale:
- name: "l_simp_chinese"
  description: "Simple Chinese"
- name: "l_english"
  description: "English"
- name: "l_braz_por"
  description: "Brazil Portuguese"
- name: "l_french"
  description: "French"
- name: "l_german"
  description: "German"
- name: "l_polish"
  description: "Polish"
- name: "l_russian"
  description: "Russian"
- name: "l_spanish"
  description: "Spanish"
- name: "l_default"
  description: "Default"

### localisation sequential number

sequentialNumber:
- name: "C"
  description: "Cardinal Number 1, 2, 3..."
  placeholderText: "1"
- name: "O"
  description: "Ordinal Number 1st, 2nd, 3rd..."
  placeholderText: "1st"
- name: "R"
  description: "Roman Number I, II, III..."
  placeholderText: "I"

### localisation color
### see: interface/fonts.gfx#bitmapfonts.textcolors

color:
- name: "M"
  description: "Purple"
  colorRgb: 0xa335ee
  colorText: "#a335ee"
- name: "L"
  description: "Brown"
  colorRgb: 0xc3b091
  colorText: "#c3b091"
- name: "G"
  description: "Green"
  colorRgb: 0x29e126
  colorText: "#29e126"
- name: "R"
  description: "Red"
  colorRgb: 0xfc5646
  colorText: "#fc5646"
- name: "B"
  description: "Blue"
  colorRgb: 0x33a7ff
  colorText: "#33a7ff"
- name: "Y"
  description: "Yellow"
  colorRgb: 0xf7fc34
  colorText: "#f7fc34"
- name: "H"
  description: "Orange"
  colorRgb: 0xfbaa29
  colorText: "#fbaa29"
- name: "T"
  description: "Light Grey"
  colorRgb: 0xffffff
  colorText: "#ffffff"
- name: "E"
  description: "Teal"
  colorRgb: 0x87ffcf
  colorText: "#87ffcf"
- name: "S"
  description: "Dark Orange"
  colorRgb: 0xe49c2a
  colorText: "#e49c2a"
- name: "W"
  description: "White"
  colorRgb: 0xffffff
  colorText: "#ffffff"
- name: "P"
  description: "Light Red"
  colorRgb: 0xe16e6e
  colorText: "#e16e6e"
- name: "g"
  description: "Grey"
  colorRgb: 0x808080
  colorText: "#808080"
- name: "l"
  description: "Light Blue"
  colorRgb: 0x33a7ff
  colorText: "#33a7ff"