l_english:
 # Comment
 text:0 "Text"
 text_empty:0 ""
 text_blank:0 " "
 text_multiline:0 "Line\nNew line"
 text_colorful:0 "Colorful text: §RRed text§!"
 text_with_parameter:0 "Parameter: $<LOCALISATION_REFERENCE>KEY</LOCALISATION_REFERENCE>$ and $WITH_COLOR|Y$\nScripted Variable: $@var$"
 text_with_command:0 "Command: [<SYSTEM_COMMAND_SCOPE>Root</SYSTEM_COMMAND_SCOPE><OPERATOR>.</OPERATOR><COMMAND_SCOPE>Owner</COMMAND_SCOPE><OPERATOR>.</OPERATOR><COMMAND_SCOPE_PREFIX>event_target:</COMMAND_SCOPE_PREFIX><DYNAMIC_VALUE>some_event_target</DYNAMIC_VALUE><OPERATOR>.</OPERATOR><COMMAND_FIELD>GetName</COMMAND_FIELD>] [<DEFINITION_REFERENCE>some_scripted_loc</DEFINITION_REFERENCE>] [<VARIABLE>some_variable</VARIABLE>]"
 text_with_concept_command:0 "Concept command: ['concept'] ['concept', concept text] ['<DATABASE_OBJECT_TYPE>civic</DATABASE_OBJECT_TYPE><MARKER>:</MARKER><DEFINITION_REFERENCE><DATABASE_OBJECT>some_civic</DATABASE_OBJECT></DEFINITION_REFERENCE>']"
 text_with_icon:0 "Icon: £unity£ and £leader_skill|3£"
 text_with_text_icon:0 "Text icon: @icon!"
 text_with_text_format:0 "Text format: #v text#!"
 text_with_variants:0 "Text|||A|||t1:B|||t2,t3:C"
 text_with_tags:0 "Text&!t1,t2"
 text_with_context_tags:0 "$1&t$ [From.GetName&t]"
