{
  parserClass="icu.windea.pls.localisation.parser.ParadoxLocalisationParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
  psiClassPrefix="ParadoxLocalisation"
  psiImplClassSuffix="Impl"
  psiPackage="icu.windea.pls.localisation.psi"
  psiImplPackage="icu.windea.pls.localisation.psi.impl"
  elementTypeHolderClass="icu.windea.pls.localisation.psi.ParadoxLocalisationElementTypes"
  tokenTypeFactory="icu.windea.pls.localisation.psi.ParadoxLocalisationElementTypeFactory.getTokenType"
  elementTypeFactory="icu.windea.pls.localisation.psi.ParadoxLocalisationElementTypeFactory.getElementType"
  psiImplUtilClass="icu.windea.pls.localisation.psi.impl.ParadoxLocalisationPsiImplUtil"
  parserUtilClass="icu.windea.pls.localisation.parser.ParadoxLocalisationParserUtil"
  methods(".*")=[getResolveScope getUseScope getPresentation toString]
  tokens=[
    EOL="<eol>"
    AT="@"
    PIPE="|"
  ]
}

// Grammar for Paradox Localisation.
// Notes:
// - Locale VS property key is resolved by the lexer.
// - Property values are lazy-parsed to support rich text features without over-tokenizing at top level.

root ::= property_list*

property_list ::= COMMENT* ( property_item_list_with_locale | property_item_list ) {
  extends="icu.windea.pls.localisation.psi.impl.ParadoxLocalisationStubElementImpl<?>"
  stubClass="icu.windea.pls.localisation.psi.stubs.ParadoxLocalisationPropertyListStub"
  implements=[
    "com.intellij.psi.PsiListLikeElement"
  ]
  methods=[
    getIcon getIElementType getComponents
  ]
}
private property_item_list_with_locale ::= locale property_items? { pin=1 }
private property_item_list ::= property_items
private property_items ::= property_item+
private property_item ::= COMMENT | property {
  // recoverWhile="#auto" // continue parsing
  recoverWhile=property_item_recover // continue parsing
}
private property_item_recover ::= !( COMMENT | LOCALE_TOKEN | PROPERTY_KEY_TOKEN )

locale ::= LOCALE_TOKEN COLON {
  pin=1
  extends="icu.windea.pls.localisation.psi.impl.ParadoxLocalisationStubElementImpl<?>"
  stubClass="icu.windea.pls.localisation.psi.stubs.ParadoxLocalisationLocaleStub"
  implements=[
    "com.intellij.psi.NavigatablePsiElement"
  ]
  methods=[
    getIdElement
    getIcon getName setName getIElementType getReference getReferences
  ]
}

property ::= property_key COLON property_number? property_value {
  pin=1
  extends="icu.windea.pls.localisation.psi.impl.ParadoxLocalisationStubElementImpl<?>"
  stubClass="icu.windea.pls.localisation.psi.stubs.ParadoxLocalisationPropertyStub"
  implements=[
    "com.intellij.psi.NavigatablePsiElement"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationNamedElement"
  ]
  methods=[
    getIcon getName setName getNameIdentifier getTextOffset getType getValue setValue getIElementType isEquivalentTo
  ]
}

property_key ::= PROPERTY_KEY_TOKEN {
  implements=[
    "com.intellij.psi.NavigatablePsiElement"
  ]
  methods=[
    getIdElement
    getIcon getName setName
  ]
}

// The number seen in vanilla files right after the colon can be omitted, as it is only useful for Paradox’s internal translation tracking
// see: https://stellaris.paradoxwikis.com/Localisation_modding
// see: https://twitter.com/Martin_Anward/status/1039175213773144066
private property_number ::= PROPERTY_NUMBER_TOKEN

// lazy-parsing PROPERTY_VALUE_TOKEN
// 3.0.2 compatible with missing opening quote and missing closing quote
property_value ::= property_value_quoted | property_value_unquoted  {
  implements=[
    "com.intellij.psi.NavigatablePsiElement"
    "icu.windea.pls.core.psi.PsiQuoteAwareElement"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationRichTextContainer"
  ]
  methods=[
    getTokenElement getRichTextList
    getQuotePattern
  ]
}
private property_value_quoted ::= LEFT_QUOTE PROPERTY_VALUE_TOKEN? RIGHT_QUOTE? { pin=1 }
private property_value_unquoted ::= PROPERTY_VALUE_TOKEN RIGHT_QUOTE?

// within localisation text rules (lazy-parsing, from PROPERTY_VALUE_TOKEN)

text_root ::= text_items {
  extraRoot=true
}
private text_items ::= text_item+
private text_item ::= rich_text | COLORFUL_TEXT_END | TEXT_FORMAT_END

rich_text ::= text | colorful_text | parameter | command | concept_command | icon | text_icon | text_format {
  implements=[
    "com.intellij.psi.NavigatablePsiElement"
    "icu.windea.pls.core.psi.PsiPresentableElement"
  ]
}

text ::= TEXT_TOKEN {
  extends=rich_text
}

// localisation colorful text rules

// see: https://stellaris.paradoxwikis.com/Localisation_modding#Color_Codes
// end marker is optional
colorful_text ::= COLORFUL_TEXT_START color_name colorful_text_items? COLORFUL_TEXT_END? {
  pin=1
  extends=rich_text
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationTextColorAwareElement"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationRichTextContainer"
  ]
  methods=[
    getIdElement
    getName setName getPresentableText getReference getReferences
  ]
}
private color_name ::= COLOR_TOKEN
private colorful_text_items ::= colorful_text_item+
private colorful_text_item ::= rich_text | TEXT_FORMAT_END

// localisation parameter rules

// see: https://stellaris.paradoxwikis.com/Localisation_modding#.24_Codes
// may be resolved to localisation / parameter / system statistics in GUI elements
parameter ::= PARAMETER_START parameter_name parameter_suffix? PARAMETER_END {
  pin=1
  extends=rich_text
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationInterpolation"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationInterpolationContainer"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationArgumentAwareElement"
  ]
  methods=[
    getIdElement getArgumentElement parameter_argument="" command=""
    getName setName getPresentableText getReference getReferences
  ]
}
// can be command or scripted variable reference
private parameter_name ::= PARAMETER_TOKEN | command | scripted_variable_reference
private parameter_suffix ::= PIPE parameter_argument?
parameter_argument ::= ARGUMENT_TOKEN {
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationArgument"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationTextColorAwareElement"
  ]
  methods=[
    getIdElement
    getReference getReferences
  ]
}
// scripted variable reference (in parameters)
scripted_variable_reference ::= AT SCRIPTED_VARIABLE_REFERENCE_TOKEN {
  implements=[
    "icu.windea.pls.lang.psi.ParadoxScriptedVariableReference"
  ]
  methods=[
    getIdElement
    getIcon getName setName getReference getReferences
  ]
}

// localisation command rules

// see: https://stellaris.paradoxwikis.com/Localisation_modding#Bracket_Commands
command ::= <<isCommand>> LEFT_BRACKET command_text? command_suffix? RIGHT_BRACKET {
  pin=2
  extends=rich_text
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationInterpolation"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationArgumentAwareElement"
  ]
  methods=[
    getArgumentElement command_argument=""
    getIcon getPresentableText
  ]
}
command_text ::= command_text_content {
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationExpressionElement"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationInterpolationContainer"
  ]
  methods=[
    getIdElement parameter=""
    getName getValue setValue setContent getPresentableText getReference getReferences
  ]
}
// can be parameterized (by using parameters)
private command_text_content ::= ( COMMAND_TEXT_TOKEN | parameter )+
private command_suffix ::= PIPE command_argument?
command_argument ::= command_argument_name {
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationArgument"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationInterpolationContainer"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationTextColorAwareElement"
  ]
  methods=[
    getIdElement parameter=""
    getReference getReferences
  ]
}
// can be parameterized (by using parameters)
private command_argument_name ::= ( ARGUMENT_TOKEN | parameter )+

// [stellaris] localisation concept command rules (as special command rules)

concept_command ::= LEFT_BRACKET LEFT_SINGLE_QUOTE concept_name? RIGHT_SINGLE_QUOTE concept_command_body? RIGHT_BRACKET {
  pin=2
  extends=rich_text
  methods=[
    getIcon getName setName getPresentableText getReference getReferences
  ]
}
concept_name ::= concept_name_content {
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationExpressionElement"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationInterpolationContainer"
  ]
  methods=[
    getIdElement parameter=""
    getName getValue setValue setContent getPresentableText getReference getReferences
  ]
}
// can be parameterized (by using parameters)
private concept_name_content ::= ( CONCEPT_NAME_TOKEN | parameter )+
private concept_command_body ::= COMMA concept_text?
concept_text ::= concept_text_items {
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationRichTextContainer"
  ]
}
private concept_text_items ::= concept_text_item+
private concept_text_item ::= rich_text | COLORFUL_TEXT_END | TEXT_FORMAT_END

// localisation icon rules

icon ::= ICON_START icon_name icon_suffix? ICON_END {
  pin=1
  extends=rich_text
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationInterpolationContainer"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationArgumentAwareElement"
  ]
  methods=[
    getIdElement getArgumentElement icon_argument="" rich_text=""
    getIcon getName setName getPresentableText getReference getReferences
  ]
}
// can be parameterized (by using parameters and commands)
private icon_name ::= ( ICON_TOKEN | parameter | command )+
private icon_suffix ::= PIPE icon_argument?
icon_argument ::= icon_argument_name {
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationArgument"
    "icu.windea.pls.localisation.psi.ParadoxLocalisationInterpolationContainer"
  ]
  methods=[
    getIdElement rich_text=""
  ]
}
// can be parameterized (by using parameters and commands)
private icon_argument_name ::= ( ARGUMENT_TOKEN | parameter | command )+

// [ck3, vic3, eu5] localisation text icon rules

text_icon ::= TEXT_ICON_START text_icon_name TEXT_ICON_END {
  pin=1
  extends=rich_text
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationInterpolationContainer"
  ]
  methods=[
    getIdElement rich_text=""
    getIcon getName setName getPresentableText getReference getReferences
  ]
}
// can be parameterized (by using parameters and commands)
private text_icon_name ::= ( TEXT_ICON_TOKEN | parameter | command )+

// [ck3, vic3, eu5] localisation text format rules

// end marker is optional
text_format ::= TEXT_FORMAT_START text_format_name text_format_text? TEXT_FORMAT_END? {
  pin=1
  extends=rich_text
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationInterpolationContainer"
  ]
  methods=[
    getIdElement rich_text=""
    getIcon getName setName getPresentableText getReference getReferences
  ]
}
// can be parameterized (by using parameters and commands)
private text_format_name ::= ( TEXT_FORMAT_TOKEN | parameter | command )+
text_format_text ::= text_format_text_items {
  implements=[
    "icu.windea.pls.localisation.psi.ParadoxLocalisationRichTextContainer"
  ]
}
private text_format_text_items ::= text_format_text_item+
private text_format_text_item ::= rich_text | COLORFUL_TEXT_END
