package icu.windea.pls.cwt.expression

enum class CwtValueExpressionType: CwtExpressionType {
	Any,
	Bool,
	Int,
	IntExpression,
	Float,
	FloatExpression,
	Scalar,
	PercentageField,
	ColorField,
	Localisation,
	SyncedLocalisation,
	InlineLocalisation,
	FilePath,
	FilePathExpression,
	IconExpression,
	DateField,
	TypeExpression,
	TypeExpressionString,
	EnumExpression,
	ScopeExpression,
	ScopeField,
	VariableField,
	VariableFieldExpression,
	IntVariableField,
	IntVariableFieldExpression,
	ValueField,
	ValueFieldExpression,
	IntValueField,
	IntValueFieldExpression,
	AliasMatchLeftExpression,
	Constant
}