package icu.windea.pls.model.constants

@Suppress("unused")
object ChronicleStrings {
    const val optionPrefix = "(option)"
    const val optionFlagPrefix = "(option flag)"
    const val complexEnumValuePrefix = "(complex enum value)"
    const val dynamicValuePrefix = "(dynamic value)"
    const val modifierPrefix = "(modifier)"
    const val scriptedVariablePrefix = "(scripted variable)"
    const val parameterPrefix = "(parameter)"
    const val definitionPrefix = "(definition)"
    const val relatedScriptedVariablePrefix = "(related scripted variable)"
    const val relatedDefinitionPrefix = "(related definition)"
    const val relatedLocalisationPrefix = "(related localisation)"
    const val relatedImagePrefix = "(related image)"
    const val generatedModifierPrefix = "(generated modifier)"
    const val eventTypePrefix = "(event type)"
    const val defineNamespacePrefix = "(define namespace)"
    const val defineVariablePrefix = "(define variable)"
    const val propertyPrefix = "(property)"
    const val valuePrefix = "(value)"
    const val sourcePropertyPrefix = "(source property)"
    const val sourceValuePrefix = "(source value)"
    const val sourcePrefix = "(source)"
    const val localePrefix = "(locale)"
    const val localisationPrefix = "(localisation)"
    const val localisationSyncedPrefix = "(synced localisation)"
    const val localisationPropertyPrefix = "(localisation property)"
    const val inlineScriptPrefix = "(inline script)"
    const val definitionInjectionPrefix = "(definition injection)"
    const val definitionInjectionTargetPrefix = "(definition injection target)"
    const val shaderEffectPrefix = "(shader effect)"
    const val meshLocatorPrefix = "(mesh locator)"

    const val yesKeyword = "yes"
    const val noKeyword = "no"
    const val blockKeyword = "{...}"

    const val parameterMarker = '$'
    const val colorMarker = '§'
    const val iconMarker = '£'

    const val parameterStartMarker = "$"
    const val parameterEndMarker = "$"
    const val inlineMathStart = "@["
    const val inlineMathEnd = "]"
    const val commandStartMarker = "["
    const val commandEndMarker = "]"
    const val colorStartMarker = "§"
    const val colorEndMarker = "§!"
    const val iconStartMarker = "£"
    const val iconEndMarker = "£"
    const val textIconStartMarker = "@"
    const val textIconEndMarker = "!"
    const val textFormatStartMarker = "#"
    const val textFormatEndMarker = "#!"

    const val headerPlaceholder = "<header>"
    const val rowPlaceholder = "<row>"

    const val commentFolder = "# ..."
    const val quotedFolder = "\"...\""
    const val blockFolder = "{...}"
    const val inlineMathFolder = "@[...]"
    fun conditionalBlockFolder(expression: String) =  "[[${expression}]...]"
    const val commandFolder = "[...]"
    const val conceptCommandFolder = "['...']"
    const val conceptCommandWithTextFolder = "['...', ...]"
    fun commandFolder(expression: String) = "[${expression}]"
    fun conceptCommandFolder(expression: String) = "['${expression}']"
    fun conceptCommandWithTextFolder(expression: String) = "['${expression}', ...]"
    fun colorfulTextFolder(name: String) = "§${name}...§!"
    fun textFormatFolder(name: String) = "#${name}...#!"
}
