package icu.windea.pls.model.constants

@Suppress("unused")
object ChronicleStrings {
    const val optionPrefix = "(option)"
    const val optionFlagPrefix = "(option flag)"
    const val complexEnumValuePrefix = "(complex enum value)"
    const val dynamicValuePrefix = "(dynamic value)"
    const val modifierPrefix = "(modifier)"
    const val scriptedVariablePrefix = "(scripted variable)"
    const val parameterPrefix = "(parameter)"
    const val definitionPrefix = "(definition)"
    const val relatedScriptedVariablePrefix = "(related scripted variable)"
    const val relatedDefinitionPrefix = "(related definition)"
    const val relatedLocalisationPrefix = "(related localisation)"
    const val relatedImagePrefix = "(related image)"
    const val generatedModifierPrefix = "(generated modifier)"
    const val eventTypePrefix = "(event type)"
    const val defineNamespacePrefix = "(define namespace)"
    const val defineVariablePrefix = "(define variable)"
    const val propertyPrefix = "(property)"
    const val valuePrefix = "(value)"
    const val sourcePropertyPrefix = "(source property)"
    const val sourceValuePrefix = "(source value)"
    const val sourcePrefix = "(source)"
    const val localePrefix = "(locale)"
    const val localisationPrefix = "(localisation)"
    const val localisationSyncedPrefix = "(synced localisation)"
    const val localisationPropertyPrefix = "(localisation property)"
    const val inlineScriptPrefix = "(inline script)"
    const val definitionInjectionPrefix = "(definition injection)"
    const val definitionInjectionTargetPrefix = "(definition injection target)"
    const val shaderEffectPrefix = "(shader effect)"
    const val meshLocatorPrefix = "(mesh locator)"

    const val yesKeyword = "yes"
    const val noKeyword = "no"

    const val parameterMarker = '$'
    const val localisationColorMarker = '§'
    const val localisationIconMarker = '£'

    const val parameterStartMarker = "$"
    const val parameterEndMarker = "$"
    const val inlineMathStart = "@["
    const val inlineMathEnd = "]"
    const val localisationParameterStartMarker = "$"
    const val localisationParameterEndMarker = "$"
    const val localisationCommandStartMarker = "["
    const val localisationCommandEndMarker = "]"
    const val localisationColorStartMarker = "§"
    const val localisationColorEndMarker = "§!"
    const val localisationIconStartMarker = "£"
    const val localisationIconEndMarker = "£"
    const val localisationTextIconStartMarker = "@"
    const val localisationTextIconEndMarker = "!"
    const val localisationTextFormatStartMarker = "#"
    const val localisationTextFormatEndMarker = "#!"

    const val headerPlaceholder = "<header>"
    const val rowPlaceholder = "<row>"

    const val commentFolder = "# ..."
    const val quotedFolder = "\"...\""
    const val blockFolder = "{...}"
    const val inlineMathFolder = "@[...]"
    fun parameterFolder(name: String) = "$${name}$"
    fun parameterWithArgFolder(name: String) = "$${name}|...$"
    fun conditionalBlockFolder(expression: String) =  "[[${expression}]...]"
    fun localisationPropertyFolder(name: String) = "${name}: \"...\""
    fun localisationParameterFolder(name: String) = "$${name}$"
    const val localisationCommandFolder = "[...]"
    fun localisationCommandFolder(expression: String) = "[${expression}]"
    const val localisationConceptCommandFolder = "['...']"
    fun localisationConceptCommandFolder(expression: String) = "['${expression}']"
    const val localisationConceptCommandWithTextFolder = "['...', ...]"
    fun localisationConceptCommandWithTextFolder(expression: String) = "['${expression}', ...]"
    fun localisationColorfulTextFolder(name: String) = "§${name}...§!"
    fun localisationTextFormatFolder(name: String) = "#${name}...#!"
}
