package icu.windea.pls.model.constants

object PlsStrings {
    const val optionPrefix = "(option)"
    const val optionFlagPrefix = "(option flag)"
    const val complexEnumValuePrefix = "(complex enum value)"
    const val dynamicValuePrefix = "(dynamic value)"
    const val modifierPrefix = "(modifier)"
    const val scriptedVariablePrefix = "(scripted variable)"
    const val parameterPrefix = "(parameter)"
    const val definitionPrefix = "(definition)"
    const val relatedScriptedVariablePrefix = "(related scripted variable)"
    const val relatedDefinitionPrefix = "(related definition)"
    const val relatedLocalisationPrefix = "(related localisation)"
    const val relatedImagePrefix = "(related image)"
    const val generatedModifierPrefix = "(generated modifier)"
    const val eventTypePrefix = "(event type)"
    const val definitionPropertyPrefix = "(definition property)"
    const val definitionValuePrefix = "(definition value)"
    const val defineNamespacePrefix = "(define namespace)"
    const val defineVariablePrefix = "(define variable)"
    const val propertyPrefix = "(property)"
    const val stringPrefix = "(string)"
    const val localePrefix = "(locale)"
    const val localisationPrefix = "(localisation)"
    const val localisationSyncedPrefix = "(localisation_synced)"
    const val localisationPropertyPrefix = "(localisation property)"
    const val localisationColorPrefix = "(localisation color)"
    const val localisationIconPrefix = "(localisation icon)"
    const val inlineScriptPrefix = "(inline script)"
    const val definitionInjectionPrefix = "(definition injection)"
    const val definitionInjectionTargetPrefix = "(definition injection target)"

    const val headerMarker = "<header>"
    const val rowMarker = "<row>"
    // const val loadingMarker = "<loading...>"

    const val commentFolder = "# ..."
    const val quotedFolder = "\"...\""
    const val blockFolder = "{...}"
    val parameterConditionFolder = { expression: String -> "[[$expression]...]" }
    const val inlineMathFolder = "@[...]"
    const val commandFolder = "[...]"
    const val conceptCommandFolder = "['...']"
    const val conceptCommandWithTextFolder = "['...', ...]"

    const val suppressInspectionsTagName = "noinspection"
}
