package icu.windea.pls.lang.util

import com.intellij.codeInsight.completion.CompletionResultSet
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiFile
import com.intellij.util.Processor
import icu.windea.pls.ChronicleFacade
import icu.windea.pls.config.config.delegated.CwtLocaleConfig
import icu.windea.pls.config.configGroup.CwtConfigGroup
import icu.windea.pls.core.annotations.Optimized
import icu.windea.pls.core.cache.CacheBuilder
import icu.windea.pls.core.cache.cancelable
import icu.windea.pls.core.cache.createNestedCache
import icu.windea.pls.core.cache.trackedBy
import icu.windea.pls.core.optimized
import icu.windea.pls.core.util.KeyRegistry
import icu.windea.pls.core.util.getOrPutUserData
import icu.windea.pls.core.util.getValue
import icu.windea.pls.core.util.provideDelegate
import icu.windea.pls.core.util.registerKey
import icu.windea.pls.core.util.registerKeyWithThis
import icu.windea.pls.ep.resolve.modifier.ParadoxModifierSupport
import icu.windea.pls.lang.codeInsight.completion.ParadoxCompletionContext
import icu.windea.pls.lang.psi.light.ParadoxModifierLightElement
import icu.windea.pls.lang.resolve.ParadoxModifierService
import icu.windea.pls.lang.selectGameType
import icu.windea.pls.lang.selectRootFile
import icu.windea.pls.localisation.psi.ParadoxLocalisationProperty
import icu.windea.pls.model.ParadoxModifierInfo
import icu.windea.pls.model.support
import icu.windea.pls.model.toInfo
import icu.windea.pls.model.toPsiElement
import icu.windea.pls.script.psi.ParadoxScriptStringExpressionElement

@Optimized
object ParadoxModifierManager {
    object Keys : KeyRegistry() {
        val modifierNameKeys by registerKey<Set<String>>(Keys)
        val modifierDescKeys by registerKey<Set<String>>(Keys)
        val modifierIconPaths by registerKey<Set<String>>(Keys)
    }

    private val CwtConfigGroup.modifierInfoCache by registerKeyWithThis(CwtConfigGroup.Keys) {
        // rootFile -> cacheKey -> modifierInfo
        // 3.0.3 use expireAfterAccess + softValues to optimize memory
        createNestedCache<VirtualFile, _, _> {
            CacheBuilder("expireAfterAccess=1h,softValues").build<String, ParadoxModifierInfo>().cancelable().trackedBy { it.modificationTracker }
        }
    }

    // We can determine which modifiers will actually be generated by running the game and checking the output `modifiers.log`
    // Different game types have some modifiers generated through different logic
    // Generated modifiers should be removed from the `modifiers.cwt` used by the plugin

    @Suppress("unused")
    fun resolveModifier(element: ParadoxScriptStringExpressionElement): ParadoxModifierLightElement? {
        val name = element.value
        val gameType = selectGameType(element) ?: return null
        val project = element.project
        val configGroup = ChronicleFacade.getConfigGroup(project, gameType)
        return resolveModifier(name, element, configGroup)
    }

    fun resolveModifier(name: String, element: PsiElement, configGroup: CwtConfigGroup, useSupport: ParadoxModifierSupport? = null): ParadoxModifierLightElement? {
        val modifierInfo = getModifierInfo(name, element, configGroup, useSupport)
        return modifierInfo?.toPsiElement(element)
    }

    fun completeModifier(context: ParadoxCompletionContext, result: CompletionResultSet) {
        if (context.contextElement !is ParadoxScriptStringExpressionElement) return
        ParadoxModifierService.completeModifier(context, result)
    }

    @Suppress("unused")
    fun processModifier(element: PsiElement, configGroup: CwtConfigGroup, processor: Processor<ParadoxModifierLightElement>): Boolean {
        return ParadoxModifierService.processModifier(element, configGroup, processor)
    }

    fun getModifierInfo(name: String, element: PsiElement, configGroup: CwtConfigGroup, useSupport: ParadoxModifierSupport? = null): ParadoxModifierInfo? {
        val rootFile = selectRootFile(element) ?: return null
        val cache = configGroup.modifierInfoCache.get(rootFile)
        val cacheKey = name // 3.0.2 #385 although modifier names are case-insensitive, cache keys here should still use vanilla input
        val modifierInfo = cache.get(cacheKey) {
            // when performing code completion, it may be necessary to use the specified extension point to resolve modifiers
            useSupport?.resolveModifier(name, element, configGroup)?.also { it.support = useSupport }
                ?: ParadoxModifierService.resolveModifier(name, element, configGroup)
                ?: ParadoxModifierInfo.EMPTY
        }
        if (modifierInfo == ParadoxModifierInfo.EMPTY) return null
        return modifierInfo
    }

    fun getModifierInfo(name: String, element: PsiElement): ParadoxModifierInfo? {
        val gameType = selectGameType(element) ?: return null
        val rootFile = selectRootFile(element) ?: return null
        val project = element.project
        val configGroup = ChronicleFacade.getConfigGroup(project, gameType)
        val cache = configGroup.modifierInfoCache.get(rootFile)
        val cacheKey = name // 3.0.2 #385 although modifier names are case-insensitive, cache keys here should still use vanilla input
        val modifierInfo = cache.get(cacheKey) {
            ParadoxModifierService.resolveModifier(name, element, configGroup) ?: ParadoxModifierInfo.EMPTY
        }
        if (modifierInfo == ParadoxModifierInfo.EMPTY) return null
        return modifierInfo
    }

    @Suppress("unused")
    fun getModifierInfo(modifierElement: ParadoxModifierLightElement): ParadoxModifierInfo? {
        val gameType = modifierElement.gameType
        val rootFile = selectRootFile(modifierElement) ?: return null
        val project = modifierElement.project
        val configGroup = ChronicleFacade.getConfigGroup(project, gameType)
        val cache = configGroup.modifierInfoCache.get(rootFile)
        val cacheKey = modifierElement.name // 3.0.2 #385 although modifier names are case-insensitive, cache keys here should still use vanilla input
        val modifierInfo = cache.get(cacheKey) {
            modifierElement.toInfo()
        }
        return modifierInfo
    }

    fun getModifierNameKeys(name: String, element: PsiElement): Set<String> {
        val modifierInfo = getModifierInfo(name, element) ?: return emptySet()
        return modifierInfo.getOrPutUserData(Keys.modifierNameKeys) {
            val result = ParadoxModifierService.getModifierNameKeys(element, modifierInfo)
            result.optimized()
        }
    }

    fun getModifierDescKeys(name: String, element: PsiElement): Set<String> {
        val modifierInfo = getModifierInfo(name, element) ?: return emptySet()
        return modifierInfo.getOrPutUserData(Keys.modifierDescKeys) {
            val result = ParadoxModifierService.getModifierDescKeys(element, modifierInfo)
            result.optimized()
        }
    }

    fun getModifierIconPaths(name: String, element: PsiElement): Set<String> {
        val modifierInfo = getModifierInfo(name, element) ?: return emptySet()
        return modifierInfo.getOrPutUserData(Keys.modifierIconPaths) {
            val result = ParadoxModifierService.getModifierIconPaths(element, modifierInfo)
            result.optimized()
        }
    }

    // region Related Items

    /**
     * 得到修正关联的所有本地化（包括名字和描述）。
     *
     * 备注：目前不经过缓存。
     *
     * @see ParadoxModifierService.resolveRelatedLocalisations
     */
    fun getRelatedLocalisations(
        element: ParadoxModifierLightElement,
        preferredLocale: CwtLocaleConfig = ParadoxLocaleManager.getPreferredLocaleConfig(),
        onlyOne: Boolean = false,
        forName: Boolean = true,
        forDesc: Boolean = true,
    ): List<ParadoxLocalisationProperty> {
        return getRelatedLocalisations(element.name, element, preferredLocale, onlyOne, forName, forDesc)
    }

    /**
     * 得到修正关联的所有本地化（包括名字和描述）。
     *
     * 备注：目前不经过缓存。
     *
     * @see ParadoxModifierService.resolveRelatedLocalisations
     */
    fun getRelatedLocalisations(
        name: String?,
        contextElement: PsiElement,
        preferredLocale: CwtLocaleConfig = ParadoxLocaleManager.getPreferredLocaleConfig(),
        onlyOne: Boolean = false,
        forName: Boolean = true,
        forDesc: Boolean = true,
    ): List<ParadoxLocalisationProperty> {
        if (name.isNullOrEmpty()) return emptyList()
        val nameKeys = if (forName) getModifierNameKeys(name, contextElement) else emptySet()
        val descKeys = if (forDesc) getModifierDescKeys(name, contextElement) else emptySet()
        return ParadoxModifierService.resolveRelatedLocalisations(nameKeys, descKeys, contextElement, preferredLocale, onlyOne)
    }

    /**
     * 得到修正关联的所有图片。
     *
     * 备注：目前不经过缓存。
     *
     * @see ParadoxModifierService.resolveRelatedImages
     */
    @Suppress("unused")
    fun getRelatedImages(
        element: ParadoxModifierLightElement,
        onlyOne: Boolean = false,
    ): List<PsiFile> {
        return getRelatedImages(element.name, element, onlyOne)
    }

    /**
     * 得到修正关联的所有图片。
     *
     * 备注：目前不经过缓存。
     *
     * @see ParadoxModifierService.resolveRelatedImages
     */
    fun getRelatedImages(
        name: String?,
        contextElement: PsiElement,
        onlyOne: Boolean = false,
    ): List<PsiFile> {
        if (name.isNullOrEmpty()) return emptyList()
        val iconPaths = getModifierIconPaths(name, contextElement)
        return ParadoxModifierService.resolveRelatedImages(iconPaths, contextElement, onlyOne)
    }

    // endregion

    // region Presentable Items

    /**
     * 得到修正的展示名字。
     */
    @Suppress("unused")
    fun getPresentableNames(
        element: ParadoxModifierLightElement,
        preferredLocale: CwtLocaleConfig = ParadoxLocaleManager.getPreferredLocaleConfig(),
        onlyOne: Boolean = false,
    ): List<String> {
        val localisation = getRelatedLocalisations(element, preferredLocale, onlyOne, forName = true, forDesc = false)
        return ParadoxLocalisationManager.getPresentableText(localisation)
    }

    /**
     * 得到修正的展示名字。
     */
    fun getPresentableNames(
        name: String,
        contextElement: PsiElement,
        preferredLocale: CwtLocaleConfig = ParadoxLocaleManager.getPreferredLocaleConfig(),
        onlyOne: Boolean = false,
    ): List<String> {
        val localisation = getRelatedLocalisations(name, contextElement, preferredLocale, onlyOne, forName = true, forDesc = false)
        return ParadoxLocalisationManager.getPresentableText(localisation)
    }

    // endregion
}
