// Copyright (c) 2021 DragonKnightOfBreeze Windea <dk_breeze@qq.com>
// All rights reserved.

// Grammar for Paradox Script.
// Notes:
// - Property separators can be comparison operators as well.

{
  parserImports="static com.intellij.lang.WhitespacesBinders.*"
  parserClass="icu.windea.pls.script.parser.ParadoxScriptParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
  psiClassPrefix="ParadoxScript"
  psiImplClassSuffix="Impl"
  psiPackage="icu.windea.pls.script.psi"
  psiImplPackage="icu.windea.pls.script.psi.impl"
  elementTypeHolderClass="icu.windea.pls.script.psi.ParadoxScriptElementTypes"
  elementTypeFactory="icu.windea.pls.script.psi.ParadoxScriptElementTypeFactory.getElementType"
  tokenTypeFactory="icu.windea.pls.script.psi.ParadoxScriptElementTypeFactory.getTokenType"
  psiImplUtilClass="icu.windea.pls.script.psi.impl.ParadoxScriptPsiImplUtil"
  parserUtilClass="icu.windea.pls.script.parser.ParadoxScriptParserUtil"
  extends("inline_math_add_expr")=inline_math_binary_expression
  methods(".*")=[getResolveScope getUseScope getPresentation toString]
  tokens=[
    EOL="<eol>"
    AT="@"
    PIPE="|"
  ]
}

// common rules

root ::= root_block?

private comment ::= COMMENT {
  name="comment"
}

root_block ::= root_block_items {
  hooks=[wsBinders="GREEDY_LEFT_BINDER, GREEDY_RIGHT_BINDER"] // surrounding whitespaces and comments are greedy
  implements=[
    "icu.windea.pls.core.psi.PsiRootBlock"
    "icu.windea.pls.script.psi.ParadoxScriptMemberContainer"
  ]
  methods=[
    getMemberContainer getMembers
    getValue getComponents
  ]
}
private root_block_items ::= root_block_item+
private root_block_item ::= comment | scripted_variable | property | value | normal_conditional_block {
  // recoverWhile="#auto" // continue parsing
  recoverWhile=root_block_item_recover // continue parsing
}
private root_block_item_recover ::= !( COMMENT
  | BOOLEAN_TOKEN | INT_TOKEN | FLOAT_TOKEN | STRING_TOKEN | PROPERTY_KEY_TOKEN
  | AT | COLOR_TOKEN | INLINE_MATH_START
  | PARAMETER_START | LEFT_BRACKET | RIGHT_BRACKET
  | LEFT_BRACE | RIGHT_BRACE
  )

// property rules

property ::= property_key property_separator property_value {
  name="property"
  pin=1
  extends="icu.windea.pls.script.psi.impl.ParadoxScriptStubElementImpl<?>"
  stubClass="icu.windea.pls.script.psi.stubs.ParadoxScriptPropertyStub"
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptNamedElement"
    "icu.windea.pls.script.psi.ParadoxScriptMember"
    "icu.windea.pls.lang.psi.ParadoxDefinitionElement"
  ]
  methods=[
    getMemberContainer getMembers getBlock property_key="property_key" property_value="value"
    getIcon getName setName getNameIdentifier getValue getIElementType isEquivalentTo getPresentableText
  ]
}
property_key ::= property_key_content {
  name="property key"
  implements=[
    "icu.windea.pls.core.psi.PsiQuoteAwareElement"
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
    "icu.windea.pls.script.psi.ParadoxScriptStringExpressionElement"
    "icu.windea.pls.script.psi.ParadoxScriptInterpolationContainer"
  ]
  methods=[
    getIdElement parameter="" inline_conditional_block=""
    getIcon getName getValue setValue setContent getPresentableText getQuotePattern getReference getReferences
  ]
}
// can be parameterized
// NOTE 3.0.2 DO NOT split out quote tokens (reduced complexity, better performance)
private property_key_content ::= property_key_part <<processLhsContent>> ( <<processPart>> property_key_part )*
private property_key_part ::= PROPERTY_KEY_TOKEN | normal_parameter | inline_conditional_block
private property_separator ::= EQUAL_SIGN | NOT_EQUAL_SIGN | LE_SIGN | GE_SIGN | LT_SIGN | GT_SIGN | SAFE_ASSIGN_SIGN | SAFE_CALL_ASSIGN_SIGN
private property_value ::= value {
  name="property value"
}

// value rules

value ::= scripted_variable_reference | boolean | int | float | string | block | color | inline_math {
  name="value"
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptExpressionElement"
    "icu.windea.pls.script.psi.ParadoxScriptMember"
  ]
  methods=[
    getIcon getName getValue setValue setContent getPresentableText
  ]
}

boolean ::= BOOLEAN_TOKEN {
  name="boolean"
  extends=value
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
  ]
}
int ::= INT_TOKEN {
  name="int"
  extends=value
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
    "icu.windea.pls.script.psi.ParadoxScriptNumberExpressionElement"
  ]
  methods=[
    getReference getReferences
  ]
}
float ::= FLOAT_TOKEN {
  name="float"
  extends=value
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
    "icu.windea.pls.script.psi.ParadoxScriptNumberExpressionElement"
  ]
  methods=[
    getReference getReferences
  ]
}
string ::= string_content {
  name="string"
  extends=value
  implements=[
    "icu.windea.pls.core.psi.PsiQuoteAwareElement"
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
    "icu.windea.pls.script.psi.ParadoxScriptStringExpressionElement"
    "icu.windea.pls.script.psi.ParadoxScriptInterpolationContainer"
  ]
  methods=[
    getIdElement parameter="" inline_conditional_block=""
    getIcon getName getValue setValue setContent getPresentableText getQuotePattern getReference getReferences
  ]
}
// can be parameterized
// NOTE 3.0.2 DO NOT split out quote tokens (reduced complexity, better performance)
private string_content ::= string_part ( <<processPart>> string_part )*
private string_part ::= STRING_TOKEN | normal_parameter | inline_conditional_block

block ::= LEFT_BRACE block_items? RIGHT_BRACE {
  pin=1
  extends=value
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptMemberContainer"
    "icu.windea.pls.script.psi.ParadoxScriptBoundMemberContainer"
  ]
  methods=[
    getMemberContainer getMembers getLeftBound getRightBound
    getIcon getValue getComponents getPresentableText getReference getReferences
  ]
}
private block_items ::= block_item+
private block_item ::= comment | scripted_variable | property | value | normal_conditional_block {
  // recoverWhile="#auto" // continue parsing
  recoverWhile=block_item_recover // continue parsing
}
private block_item_recover ::= !( COMMENT
  | BOOLEAN_TOKEN | INT_TOKEN | FLOAT_TOKEN | STRING_TOKEN | PROPERTY_KEY_TOKEN
  | AT | COLOR_TOKEN | INLINE_MATH_START
  | PARAMETER_START | LEFT_BRACKET | RIGHT_BRACKET
  | LEFT_BRACE | RIGHT_BRACE
  )

// advanced script syntax
// see: common/scripted_effects/99_advanced_documentation.txt
// see wiki: https://stellaris.paradoxwikis.com/Dynamic_modding

// scripted variable rules

// scripted variable
scripted_variable ::= scripted_variable_name scripted_variable_separator scripted_variable_value {
  name="scripted variable"
  pin=1
  extends="icu.windea.pls.script.psi.impl.ParadoxScriptStubElementImpl<?>"
  stubClass="icu.windea.pls.script.psi.stubs.ParadoxScriptScriptedVariableStub"
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptNamedElement"
    "icu.windea.pls.script.psi.ParadoxScriptStatement"
  ]
  methods=[
    scripted_variable_name="scripted_variable_name" scripted_variable_value="value"
    getIcon getName setName getNameIdentifier getTextOffset getValue getIElementType isEquivalentTo getPresentableText
  ]
}
scripted_variable_name ::= AT <<processLhsContent>> scripted_variable_name_content {
  name="scripted variable name"
  pin=2
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptInterpolationContainer"
  ]
  methods=[
    getIdElement parameter="" inline_conditional_block=""
    getName
  ]
}
// can be parameterized
private scripted_variable_name_content ::= scripted_variable_name_part ( <<processPart>> scripted_variable_name_part )*
private scripted_variable_name_part ::= SCRIPTED_VARIABLE_NAME_TOKEN | normal_parameter | inline_conditional_block
private scripted_variable_separator ::= EQUAL_SIGN
private scripted_variable_value ::= boolean | int | float | string | inline_math { // limited
  name="scripted variable value"
}

// scripted variable reference
scripted_variable_reference ::= AT scripted_variable_reference_content {
  name="scripted variable reference"
  pin=1
  extends=value
  implements=[
    "icu.windea.pls.lang.psi.ParadoxScriptedVariableReference"
    "icu.windea.pls.script.psi.ParadoxScriptInterpolationContainer"
  ]
  methods=[
    getIdElement parameter="" inline_conditional_block=""
    getIcon getName setName getValue getPresentableText getReference getReferences
  ]
}
// can be parameterized
private scripted_variable_reference_content ::= scripted_variable_reference_part ( <<processPart>> scripted_variable_reference_part )*
private scripted_variable_reference_part ::= SCRIPTED_VARIABLE_REFERENCE_TOKEN | normal_parameter | inline_conditional_block

// color rules

// TODO 3.0.2+ better syntax support: split into more specific tokens (distinct from normal keywords/identifiers and normal blocks)
color ::= COLOR_TOKEN {
  name="color"
  extends=value
  methods=[
    getColorType getColorArgs getColor setColor
  ]
}

// inline math rules

// description:
// - should in definition declaration
// - should starts with `@\[` if in specific definition declaration (scripted_effect / scripted_trigger) (TO CHECK)
// - supported operators: + - * / %
// - also support unary operators `+1` `-1`, abs operator `| 1 |` and parentheses `( 1 )`
// - inline math factor can also be scripted_variable and (if parameter it self is allowed) parameter

// lazy-parsing INLINE_MATH_TOKEN
inline_math ::= INLINE_MATH_START INLINE_MATH_TOKEN INLINE_MATH_END {
  name="inline math"
  pin=1
  extends=value
  implements=[
    "icu.windea.pls.core.psi.PsiBoundElement"
  ]
  methods=[
    getTokenElement getInlineMathExpression getLeftBound getRightBound
    getValue getPresentableText
  ]
}

// tag rules

// resolved at semantic level
// from a string which is a direct value

// parameter rules

// can be used in:
// - keys (can be quoted)
// - values (can be quoted)
// - scripted variable names
// - scripted variable reference names
// - inline math expressions

normal_parameter ::= PARAMETER_START parameter_name parameter_argument_part? PARAMETER_END {
  name="parameter"
  pin=1
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptParameter"
    "icu.windea.pls.script.psi.ParadoxScriptInterpolation"
    "icu.windea.pls.script.psi.ParadoxScriptArgumentAwareElement"
  ]
  methods=[
    getIdElement getArgumentElement parameter_argument=""
    getIcon getName setName getTextOffset getDefaultValue getReference getReferences getPresentableText
  ]
}

private parameter_name ::= PARAMETER_TOKEN
private parameter_argument_part ::= PIPE parameter_argument?
parameter_argument ::= ARGUMENT_TOKEN {
  name="parameter argument"
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptArgument"
  ]
  methods=[
    getIdElement
  ]
}

// conditional block rules

// should in definition declaration (script_value / scripted_effect / scripted_trigger)
normal_conditional_block ::= LEFT_BRACKET conditional_header normal_conditional_block_items? RIGHT_BRACKET {
  name="conditional block"
  pin=1
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptConditionalBlock"
    "icu.windea.pls.script.psi.ParadoxScriptStatement"
    "icu.windea.pls.script.psi.ParadoxScriptMemberContainer"
    "icu.windea.pls.script.psi.ParadoxScriptBoundMemberContainer"
  ]
  methods=[
    getMemberContainer getMembers getLeftBound getRightBound
    getIcon getComponents getPresentableText
  ]
}
private normal_conditional_block_items ::= normal_conditional_block_item+
private normal_conditional_block_item ::= comment/* | scripted_variable*/ | property | value | normal_conditional_block {
  // recoverWhile="#auto" // continue parsing
  recoverWhile=normal_conditional_block_item_recover // continue parsing
}
private normal_conditional_block_item_recover ::= !( COMMENT
  | BOOLEAN_TOKEN | INT_TOKEN | FLOAT_TOKEN | STRING_TOKEN | PROPERTY_KEY_TOKEN
  | AT | COLOR_TOKEN | INLINE_MATH_START
  | PARAMETER_START | LEFT_BRACKET | RIGHT_BRACKET
  | LEFT_BRACE | RIGHT_BRACE
  )

// used in, such as, dynamic strings (e.g. `a[[b]c]d`)
inline_conditional_block ::= LEFT_BRACKET <<processInlineConditionalBlock>> conditional_header inline_conditional_block_item? RIGHT_BRACKET {
  name="inline conditional block"
  pin=2
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptConditionalBlock"
    "icu.windea.pls.script.psi.ParadoxScriptInterpolation"
    "icu.windea.pls.script.psi.ParadoxScriptInterpolationContainer"
  ]
  methods=[
    getLeftBound getRightBound parameter="" inline_conditional_block=""
    getIcon getPresentableText
  ]
}
private inline_conditional_block_item ::= inline_conditional_block_item_content {
  // recoverWhile="#auto" // continue parsing
  recoverWhile=inline_normal_conditional_block_item_recover // continue parsing
}
private inline_conditional_block_item_content ::= inline_conditional_block_item_part ( <<processPart>> inline_conditional_block_item_part )*
private inline_conditional_block_item_part ::= inline_conditional_block_item_token | normal_parameter | inline_conditional_block
private inline_conditional_block_item_token ::= PROPERTY_KEY_TOKEN | STRING_TOKEN | SCRIPTED_VARIABLE_NAME_TOKEN | SCRIPTED_VARIABLE_REFERENCE_TOKEN
private inline_normal_conditional_block_item_recover ::= !( COMMENT
  | BOOLEAN_TOKEN | INT_TOKEN | FLOAT_TOKEN | STRING_TOKEN | PROPERTY_KEY_TOKEN
  | AT | COLOR_TOKEN | INLINE_MATH_START
  | PARAMETER_START | LEFT_BRACKET | RIGHT_BRACKET
  | LEFT_BRACE | RIGHT_BRACE
  )

private conditional_header ::= NESTED_LEFT_BRACKET conditional_expression NESTED_RIGHT_BRACKET {
  pin=1
}
conditional_expression ::= NOT_SIGN? conditional_parameter {
  implements="icu.windea.pls.core.psi.PsiPresentableElement"
  methods=[
    getPresentableText
  ]
}
conditional_parameter ::= CONDITION_PARAMETER_TOKEN {
  name="conditional parameter"
  implements="icu.windea.pls.script.psi.ParadoxScriptConditionParameter"
  methods=[
    getIdElement
    getIcon getName setName getTextOffset getReference getReferences
  ]
}

// within inline math rules (lazy-parsing, from INLINE_MATH_TOKEN)

inline_math_root ::= inline_math_expr {
  extraRoot=true
}

// precedence-sensitive
private inline_math_expr ::= inline_math_expr_term
private inline_math_expr_term ::= inline_math_expr_factor inline_math_add_expr*
private inline_math_expr_factor ::= inline_math_expr_unary inline_math_mul_expr*
private inline_math_expr_unary ::= inline_math_unary_expression | inline_math_expr_primary
private inline_math_expr_primary ::= inline_math_grouping_expression | inline_math_factor

// noinspection BnfUnusedRule
inline_math_expression ::= inline_math_binary_expression | inline_math_unary_expression | inline_math_grouping_expression | inline_math_factor

inline_math_unary_expression ::= inline_math_unary_op inline_math_unary_factor {
  pin=1
  extends=inline_math_expression
}
private inline_math_unary_op ::= PLUS_SIGN | MINUS_SIGN
private inline_math_unary_factor ::= inline_math_grouping_expression | inline_math_factor

inline_math_binary_expression ::= inline_math_add_expr | inline_math_mul_expr {
  pin=2
  extends=inline_math_expression
}
left inline_math_add_expr ::= inline_math_add_op inline_math_expr_factor {
  pin=1
  elementType=inline_math_binary_expression // the intended way to override element type
}
left inline_math_mul_expr ::= inline_math_mul_op inline_math_expr_unary {
  pin=1
  elementType=inline_math_binary_expression // the intended way to override element type
}
private inline_math_add_op ::= PLUS_SIGN | MINUS_SIGN
private inline_math_mul_op ::= TIMES_SIGN | DIV_SIGN | MOD_SIGN

inline_math_grouping_expression ::= inline_math_par_expr | inline_math_abs_expr {
  extends=inline_math_expression
}
private inline_math_par_expr ::= LP_SIGN inline_math_expr RP_SIGN {
pin=1
}
private inline_math_abs_expr ::= LABS_SIGN inline_math_expr RABS_SIGN {
pin=1
}

// order: `1` -> `$PARAM$_part` -> `$PARAM$`
inline_math_factor ::= inline_math_number | inline_math_scripted_variable_reference | inline_math_parameter {
  extends=inline_math_expression
}

inline_math_number ::= INT_NUMBER_TOKEN | FLOAT_NUMBER_TOKEN {
  name="inline math number"
  extends=inline_math_factor
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
  ]
  methods=[
    getIcon getValue
  ]
}

/// leading `@` is allowed here at syntax level (but not valid in actual)
inline_math_scripted_variable_reference ::= AT? inline_math_scripted_variable_reference_content {
  name="inline math scripted variable reference"
  extends=inline_math_factor
  implements=[
    "icu.windea.pls.lang.psi.ParadoxScriptedVariableReference"
    "icu.windea.pls.script.psi.ParadoxScriptInterpolationContainer"
  ]
  methods=[
    getIdElement inline_math_parameter="" inline_conditional_block=""
    getIcon getName setName getReference getReferences
  ]
}
// can be parameterized
private inline_math_scripted_variable_reference_content ::= inline_math_scripted_variable_reference_part ( <<processPart>> inline_math_scripted_variable_reference_part )*
private inline_math_scripted_variable_reference_part ::= SCRIPTED_VARIABLE_REFERENCE_TOKEN | inline_math_parameter

inline_math_parameter ::= PARAMETER_START parameter_name parameter_argument_part? PARAMETER_END {
  name="inline math parameter"
  extends=inline_math_factor
  pin=1
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptParameter"
    "icu.windea.pls.script.psi.ParadoxScriptInterpolation"
    "icu.windea.pls.script.psi.ParadoxScriptArgumentAwareElement"
  ]
  methods=[
    getIdElement getArgumentElement parameter_argument=""
    getIcon getName setName getTextOffset getDefaultValue getReference getReferences getPresentableText
  ]
}
