{
  parserImports="static com.intellij.lang.WhitespacesBinders.*"
  parserClass="icu.windea.pls.script.parser.ParadoxScriptParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
  psiClassPrefix="ParadoxScript"
  psiImplClassSuffix="Impl"
  psiPackage="icu.windea.pls.script.psi"
  psiImplPackage="icu.windea.pls.script.psi.impl"
  elementTypeHolderClass="icu.windea.pls.script.psi.ParadoxScriptElementTypes"
  elementTypeFactory="icu.windea.pls.script.psi.ParadoxScriptElementTypeFactory.getElementType"
  tokenTypeFactory="icu.windea.pls.script.psi.ParadoxScriptElementTypeFactory.getTokenType"
  psiImplUtilClass="icu.windea.pls.script.psi.impl.ParadoxScriptPsiImplUtil"
  parserUtilClass="icu.windea.pls.script.parser.ParadoxScriptParserUtil"
  tokens=[
    AT="@"
    PIPE="|"
  ]
  methods(".*")=[getResolveScope getUseScope getPresentation toString]
  extends("inline_math_add_expr")=inline_math_binary_expression
}

// Grammar for Paradox Script.
// Notes:
// - Property separators can be comparison operators as well.

root ::= root_block ?
root_block ::= root_block_item + {
  hooks=[wsBinders="GREEDY_LEFT_BINDER, GREEDY_RIGHT_BINDER"]
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptMemberContainer"
  ]
  methods=[getMemberContainer getMembers getComponents]
}
private root_block_item ::= COMMENT | root_block_value | property | scripted_variable | conditional_block
private root_block_value ::= scripted_variable_reference | boolean | int | float | string | color | block | inline_math

// scripted_variable
scripted_variable ::= scripted_variable_name scripted_variable_separator scripted_variable_value {
  pin=1
  recoverWhile="#auto" // continue parsing
  extends="icu.windea.pls.script.psi.impl.ParadoxScriptStubElementImpl<?>"
  stubClass="icu.windea.pls.script.psi.stubs.ParadoxScriptScriptedVariableStub"
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptNamedElement"
    "icu.windea.pls.script.psi.ParadoxScriptStatement"
  ]
  methods=[
    scripted_variable_name="scripted_variable_name" scripted_variable_value="value"
    getIcon getName setName getNameIdentifier getTextOffset getValue
    getIElementType isEquivalentTo
  ]
}
// can be parameterized
scripted_variable_name ::= AT scripted_variable_name_part (<<processSnippet>> scripted_variable_name_part) * {
  pin=1
  implements=[
    "icu.windea.pls.script.psi.ParadoxParameterAwareElement"
  ]
  methods=[getIdElement parameter="" getName]
}
private scripted_variable_name_part ::= SCRIPTED_VARIABLE_NAME_TOKEN | parameter | inline_conditional_block
private scripted_variable_separator ::= EQUAL_SIGN
private scripted_variable_value ::= boolean | int | float | string | inline_math

// property related
property ::= property_key property_separator property_value {
  pin=1
  recoverWhile="#auto" // continue parsing
  extends="icu.windea.pls.script.psi.impl.ParadoxScriptStubElementImpl<?>"
  stubClass="icu.windea.pls.script.psi.stubs.ParadoxScriptPropertyStub"
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptNamedElement"
    "icu.windea.pls.script.psi.ParadoxScriptMember"
    "icu.windea.pls.script.psi.ParadoxDefinitionElement"
  ]
  methods=[
    property_key="property_key" property_value="value"
    getIcon getName setName getNameIdentifier getValue getExpression getBlock
    getIElementType isEquivalentTo
    getMemberContainer getMembers

  ]
}
// can be parameterized
property_key ::= property_key_part (<<processSnippet>> property_key_part) * {
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
    "icu.windea.pls.script.psi.ParadoxScriptStringExpressionElement"
    "icu.windea.pls.script.psi.ParadoxParameterAwareElement"
  ]
  methods=[
    getIdElement parameter=""
    getIcon getName getValue setValue getExpression
    getReference getReferences
  ]
}
private property_key_part ::= PROPERTY_KEY_TOKEN | parameter | inline_conditional_block
private property_separator ::= EQUAL_SIGN | LT_SIGN | GT_SIGN | LE_SIGN | GE_SIGN | NOT_EQUAL_SIGN | SAFE_ASSIGN_SIGN | SAFE_CALL_ASSIGN_SIGN
private property_value ::= scripted_variable_reference | boolean | int | float | string | color | block | inline_math

// value related
// noinspection BnfUnusedRule
value ::= scripted_variable_reference | boolean | int | float | string | color | block | inline_math {
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptExpressionElement"
    "icu.windea.pls.script.psi.ParadoxScriptMember"
  ]
  methods=[getIcon getName getValue setValue getExpression]
}
// can be parameterized
scripted_variable_reference ::= AT scripted_variable_reference_part <<postProcessFirstSnippet>> (<<processSnippet>> scripted_variable_reference_part) * {
  extends=value
  implements=[
    "icu.windea.pls.lang.psi.ParadoxScriptedVariableReference"
    "icu.windea.pls.script.psi.ParadoxParameterAwareElement"
  ]
  methods=[
    getIdElement parameter=""
    getIcon getName setName getValue setValue getExpression getReference getReferences
  ]
}
private scripted_variable_reference_part ::= SCRIPTED_VARIABLE_REFERENCE_TOKEN | parameter | inline_conditional_block
boolean ::= BOOLEAN_TOKEN {
  extends=value
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
  ]
}
int ::= INT_TOKEN {
  extends=value
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
    "icu.windea.pls.script.psi.ParadoxScriptNumberExpressionElement"
  ]
  methods=[getReference getReferences]
}
float ::= FLOAT_TOKEN {
  extends=value
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
    "icu.windea.pls.script.psi.ParadoxScriptNumberExpressionElement"
  ]
  methods=[getReference getReferences]
}
// can be parameterized
string ::= string_part <<postProcessFirstSnippet>> (<<processSnippet>> string_part) * {
  extends=value
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
    "icu.windea.pls.script.psi.ParadoxScriptStringExpressionElement"
    "icu.windea.pls.script.psi.ParadoxParameterAwareElement"
  ]
  methods=[
    getIdElement parameter=""
    getIcon getValue setValue
    getReference getReferences
  ]
}
private string_part ::= STRING_TOKEN | parameter | inline_conditional_block
color ::= COLOR_TOKEN {
  extends=value
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
  ]
  methods=[getColorType getColorArgs getColor setColor]
}
block ::= LEFT_BRACE block_item * RIGHT_BRACE {
  pin=1
  extends=value
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptMemberContainer"
    "icu.windea.pls.script.psi.ParadoxScriptBoundMemberContainer"
  ]
  methods=[
    getIcon getValue getExpression getReference getReferences
    getMemberContainer getMembers getLeftBound getRightBound getComponents
  ]
}
private block_item ::= COMMENT | block_value | property | scripted_variable | conditional_block {
  recoverWhile="#auto" // continue parsing
}
private block_value ::= scripted_variable_reference | boolean | int | float | string | color | block | inline_math

// advanced script syntax
// see: common/scripted_effects/99_advanced_documentation.txt
// see wiki: https://stellaris.paradoxwikis.com/Dynamic_modding

// tag
// should in definition declaration (scripted_effect / scripted_trigger)
// resolved from a string, before any scripted variables, (non-tag) strings and properties

// parameter rules

// Currently, parameters can be used in:
// - scripted variable names
// - scripted variable reference names
// - keys (can be quoted)
// - values (can be quoted)
// - inline math expressions

parameter ::= PARAMETER_START parameter_name parameter_argument_part ? PARAMETER_END {
  pin=1
  implements=[
    "icu.windea.pls.script.psi.ParadoxParameter"
    "icu.windea.pls.script.psi.ParadoxArgumentAwareElement"
  ]
  methods=[
    getIdElement getArgumentElement parameter_argument=""
    getIcon getName setName getTextOffset getDefaultValue getReference
  ]
}
inline_math_parameter ::= PARAMETER_START parameter_name parameter_argument_part ? PARAMETER_END {
  extends=inline_math_factor
  pin=1
  implements=[
    "icu.windea.pls.script.psi.ParadoxParameter"
    "icu.windea.pls.script.psi.ParadoxArgumentAwareElement"
  ]
  methods=[
    getIdElement getArgumentElement parameter_argument=""
    getIcon getName setName getTextOffset getDefaultValue getReference
  ]
}
private parameter_name ::= PARAMETER_TOKEN
private parameter_argument_part ::= PIPE parameter_argument ?
parameter_argument ::= ARGUMENT_TOKEN {
  implements=[
    "icu.windea.pls.script.psi.ParadoxArgument"
  ]
  methods=[getIdElement]
}

// conditional block rules

// conditional block
// should in definition declaration (script_value / scripted_effect / scripted_trigger)
conditional_block ::= LEFT_BRACKET conditional_block_expr conditional_block_item * RIGHT_BRACKET {
  pin=1
  recoverWhile="#auto" // continue parsing
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptStatement"
    "icu.windea.pls.script.psi.ParadoxScriptMemberContainer"
    "icu.windea.pls.script.psi.ParadoxScriptBoundMemberContainer"
  ]
  methods=[
    getIcon getConditionExpression getPresentationText
    getMemberContainer getMembers getLeftBound getRightBound getComponents
  ]
}
private conditional_block_expr ::= NESTED_LEFT_BRACKET conditional_block_expression NESTED_RIGHT_BRACKET {
  pin=1
}
conditional_block_expression ::= NOT_SIGN ? conditional_block_parameter
conditional_block_parameter ::= CONDITION_PARAMETER_TOKEN {
  implements="icu.windea.pls.script.psi.ParadoxConditionParameter"
  methods=[getIdElement getIcon getName setName getTextOffset getReference]
}
private conditional_block_item ::= COMMENT | conditional_block_value | property | conditional_block {
  recoverWhile="#auto" // continue parsing
}
private conditional_block_value ::= scripted_variable_reference | boolean | int | float | string | color | block | inline_math

// inline conditional block
// used in, such as, dynamic strings (e.g. "a[[b]c]d")
inline_conditional_block ::= LEFT_BRACKET <<processInlineConditionalBlock>> conditional_block_expr inline_conditional_block_item RIGHT_BRACKET {
  pin=2
  implements=[
    "icu.windea.pls.core.psi.PsiBoundElement"
  ]
  methods=[getIcon getConditionExpression getPresentationText getLeftBound getRightBound]
}
private inline_conditional_block_item ::= <<processInlineConditionalBlockItem>> inline_conditional_block_snippet <<postProcessInlineConditionalBlockItem>>
private inline_conditional_block_snippet ::= inline_conditional_block_item_part (<<processSnippet>> inline_conditional_block_item_part) *
private inline_conditional_block_item_part ::= ARGUMENT_TOKEN | parameter | inline_conditional_block

// inline math rules

// inline math
// should in definition declaration
// should starts with "@\[" if in specific definition declaration (scripted_effect / scripted_trigger) (TO CHECK)
// only first inline math expression in a scripted effect / trigger is correctly recognized and evaluated
// supported operators: + - * / %
// also support unary operators "+1" "-1", abs operator "| 1 |" and parentheses "( 1 )"
// inline math factor can also be scripted_variable and (if parameter it self is allowed) parameter

inline_math ::= INLINE_MATH_START INLINE_MATH_TOKEN INLINE_MATH_END { // lazy-parsing INLINE_MATH_TOKEN
  pin=1
  extends=value
  implements=[
    "icu.windea.pls.core.psi.PsiBoundElement"
  ]
  methods=[getValue getExpression getTokenElement getInlineMathExpression getLeftBound getRightBound]
}

// ------

// inline math expression rules (lazy-parsing, from INLINE_MATH_TOKEN)

inline_math_root ::= inline_math_expr {
  extraRoot=true
}

// precedence-sensitive
private inline_math_expr ::= inline_math_expr_term
private inline_math_expr_term ::= inline_math_expr_factor inline_math_add_expr *
private inline_math_expr_factor ::= inline_math_expr_unary inline_math_mul_expr *
private inline_math_expr_unary ::= inline_math_unary_expression | inline_math_expr_primary
private inline_math_expr_primary ::= inline_math_grouping_expression | inline_math_factor

// noinspection BnfUnusedRule
inline_math_expression ::= inline_math_binary_expression | inline_math_unary_expression | inline_math_grouping_expression | inline_math_factor

inline_math_unary_expression ::= inline_math_unary_op inline_math_unary_factor {
  pin=1
  extends=inline_math_expression
}
private inline_math_unary_op ::= PLUS_SIGN | MINUS_SIGN
private inline_math_unary_factor ::= inline_math_grouping_expression | inline_math_factor

inline_math_binary_expression ::= inline_math_add_expr | inline_math_mul_expr {
  pin=2
  extends=inline_math_expression
}
left inline_math_add_expr ::= inline_math_add_op inline_math_expr_factor {
  pin=1
  elementType=inline_math_binary_expression
}
left inline_math_mul_expr ::= inline_math_mul_op inline_math_expr_unary {
  pin=1
  elementType=inline_math_binary_expression
}
private inline_math_add_op ::= PLUS_SIGN | MINUS_SIGN
private inline_math_mul_op ::= TIMES_SIGN | DIV_SIGN | MOD_SIGN

inline_math_grouping_expression ::= inline_math_par_expr | inline_math_abs_expr {
  extends=inline_math_expression
}
private inline_math_par_expr ::= LP_SIGN inline_math_expr RP_SIGN {
pin=1
}
private inline_math_abs_expr ::= LABS_SIGN inline_math_expr RABS_SIGN {
pin=1
}

// order: `1` -> `$PARAM$_part` -> `$PARAM$`
inline_math_factor ::= inline_math_number | inline_math_scripted_variable_reference | inline_math_parameter {
  extends=inline_math_expression
}
inline_math_number ::= INT_NUMBER_TOKEN | FLOAT_NUMBER_TOKEN {
  extends=inline_math_factor
  implements=[
    "icu.windea.pls.script.psi.ParadoxScriptLiteralValue"
  ]
  methods=[getValue]
}
// leading `@` is permitted (on syntax level)
// can be parameterized
inline_math_scripted_variable_reference ::= AT ? inline_math_scripted_variable_reference_part <<postProcessFirstSnippet>> (<<processSnippet>> inline_math_scripted_variable_reference_part) * {
  extends=inline_math_factor
  implements=[
    "icu.windea.pls.lang.psi.ParadoxScriptedVariableReference"
    "icu.windea.pls.script.psi.ParadoxParameterAwareElement"
  ]
  methods=[
    getIdElement inline_math_parameter=""
    getIcon getName setName getReference getReferences
  ]
}
private inline_math_scripted_variable_reference_part ::= SCRIPTED_VARIABLE_REFERENCE_TOKEN | inline_math_parameter
