@file:Suppress("unused")

package icu.windea.pls.ep.resolve.parameter

import com.intellij.psi.SmartPsiElementPointer
import icu.windea.pls.core.util.getValue
import icu.windea.pls.core.util.provideDelegate
import icu.windea.pls.core.util.registerKey
import icu.windea.pls.core.util.setValue
import icu.windea.pls.core.util.withSync
import icu.windea.pls.lang.psi.light.ParadoxParameterLightElement
import icu.windea.pls.model.ParadoxParameterContextReferenceInfo
import icu.windea.pls.model.ParadoxParameterInfo
import icu.windea.pls.script.psi.ParadoxDefinitionElement

val ParadoxParameterSupport.Keys.support by registerKey<ParadoxParameterSupport>(ParadoxParameterSupport.Keys).withSync()
val ParadoxParameterSupport.Keys.containingContext by registerKey<SmartPsiElementPointer<ParadoxDefinitionElement>>(ParadoxParameterSupport.Keys).withSync()
val ParadoxParameterSupport.Keys.containingContextReference by registerKey<SmartPsiElementPointer<ParadoxDefinitionElement>>(ParadoxParameterSupport.Keys).withSync()
val ParadoxParameterSupport.Keys.definitionName by registerKey<String>(ParadoxParameterSupport.Keys).withSync()
val ParadoxParameterSupport.Keys.definitionTypes by registerKey<List<String>>(ParadoxParameterSupport.Keys).withSync()
val ParadoxParameterSupport.Keys.inlineScriptExpression by registerKey<String>(ParadoxParameterSupport.Keys).withSync()

var ParadoxParameterInfo.support by ParadoxParameterSupport.Keys.support
var ParadoxParameterInfo.definitionName by ParadoxParameterSupport.Keys.definitionName
var ParadoxParameterInfo.definitionTypes by ParadoxParameterSupport.Keys.definitionTypes
var ParadoxParameterInfo.inlineScriptExpression by ParadoxParameterSupport.Keys.inlineScriptExpression

var ParadoxParameterLightElement.support by ParadoxParameterSupport.Keys.support
var ParadoxParameterLightElement.containingContext by ParadoxParameterSupport.Keys.containingContext
var ParadoxParameterLightElement.containingContextReference by ParadoxParameterSupport.Keys.containingContextReference
var ParadoxParameterLightElement.definitionName by ParadoxParameterSupport.Keys.definitionName
var ParadoxParameterLightElement.definitionTypes by ParadoxParameterSupport.Keys.definitionTypes
var ParadoxParameterLightElement.inlineScriptExpression by ParadoxParameterSupport.Keys.inlineScriptExpression

var ParadoxParameterContextReferenceInfo.support by ParadoxParameterSupport.Keys.support
var ParadoxParameterContextReferenceInfo.containingContext by ParadoxParameterSupport.Keys.containingContext
var ParadoxParameterContextReferenceInfo.containingContextReference by ParadoxParameterSupport.Keys.containingContextReference
var ParadoxParameterContextReferenceInfo.definitionName by ParadoxParameterSupport.Keys.definitionName
var ParadoxParameterContextReferenceInfo.definitionTypes by ParadoxParameterSupport.Keys.definitionTypes
var ParadoxParameterContextReferenceInfo.inlineScriptExpression by ParadoxParameterSupport.Keys.inlineScriptExpression
