### localisation locale
  
locale:
- id: "l_simp_chinese"
  description: "Simple Chinese"
- id: "l_english"
  description: "English"
- id: "l_braz_por"
  description: "Brazil Portuguese"
- id: "l_french"
  description: "French"
- id: "l_german"
  description: "German"
- id: "l_polish"
  description: "Polish"
- id: "l_russian"
  description: "Russian"
- id: "l_spanish"
  description: "Spanish"
- id: "l_default"
  description: "Default"

### localisation sequential number

sequentialNumber:
- id: "C"
  description: "Cardinal Number 1, 2, 3..."
  placeholderText: "1"
- id: "O"
  description: "Ordinal Number 1st, 2nd, 3rd..."
  placeholderText: "1st"
- id: "R"
  description: "Roman Number I, II, III..."
  placeholderText: "I"

### localisation color
### see: interface/fonts.gfx#bitmapfonts.textcolors

color:
- id: "M"
  description: "Purple"
  colorRgb: 0xa335ee
  colorText: "#a335ee"
- id: "L"
  description: "Brown"
  colorRgb: 0xc3b091
  colorText: "#c3b091"
- id: "G"
  description: "Green"
  colorRgb: 0x29e126
  colorText: "#29e126"
- id: "R"
  description: "Red"
  colorRgb: 0xfc5646
  colorText: "#fc5646"
- id: "B"
  description: "Blue"
  colorRgb: 0x33a7ff
  colorText: "#33a7ff"
- id: "Y"
  description: "Yellow"
  colorRgb: 0xf7fc34
  colorText: "#f7fc34"
- id: "H"
  description: "Orange"
  colorRgb: 0xfbaa29
  colorText: "#fbaa29"
- id: "T"
  description: "Light Grey"
  colorRgb: 0xffffff
  colorText: "#ffffff"
- id: "E"
  description: "Teal"
  colorRgb: 0x87ffcf
  colorText: "#87ffcf"
- id: "S"
  description: "Dark Orange"
  colorRgb: 0xe49c2a
  colorText: "#e49c2a"
- id: "W"
  description: "White"
  colorRgb: 0xffffff
  colorText: "#ffffff"
- id: "P"
  description: "Light Red"
  colorRgb: 0xe16e6e
  colorText: "#e16e6e"
- id: "g"
  description: "Grey"
  colorRgb: 0x808080
  colorText: "#808080"
- id: "l"
  description: "Light Blue"
  colorRgb: 0x33a7ff
  colorText: "#33a7ff"