name: Auto assign new issues and PRs

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Assign to me if unassigned
        uses: actions/github-script@v8
        with:
          script: |
            const { owner, repo } = context.repo;
            const payload = context.payload;
            
            let number, assignees;
            
            if (payload.issue) {
              number = payload.issue.number;
              assignees = payload.issue.assignees;
            } else if (payload.pull_request) {
              number = payload.pull_request.number;
              assignees = payload.pull_request.assignees;
            } else {
              return;
            }
            
            // 检查是否已有分配者
            if (assignees && assignees.length > 0) {
              console.log(`Already assigned: ${assignees.map(a => a.login).join(', ')}`);
              return;
            }
            
            // 分配给仓库所有者
            const assign_to = owner;
            console.log(`Assigning #${number} to @${assign_to}`);
            
            await github.rest.issues.addAssignees({
              owner: owner,
              repo: repo,
              issue_number: number,
              assignees: [assign_to]
            });
