name: Auto assign new issues and PRs

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to me if unassigned
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const payload = context.payload;
            if (payload.issue) {
              const number = payload.issue.number;
              const assignees = payload.issue.assignees;
              if (assignees && assignees.length > 0) return;
              const assign_to = owner;
              core.info(`Assigning issue #${issueNumber} to @${assign_to}`);
              await github.rest.issues.addAssignees({
                owner: owner,
                repo: repo,
                issue_number: number,
                assignees: [assign_to]
              }
            } else if(payload.pull_request) {
              const number = payload.pull_request.number;
              const assignees = payload.pull_request.assignees;
              if (assignees && assignees.length > 0) return;
              const assign_to = owner;
              core.info(`Assigning pull request #${number} to @${assign_to}`);
              await github.rest.issues.addAssignees({
                owner: owner,
                repo: repo,
                issue_number: number,
                assignees: [assign_to]
              });
            }
